      * WSD copybook for PROPRIETPROVDS (auto-generated)
       01  PROPRIETPROVDS.
           05  PROPRIETPROVDS-ROWID           PIC X(018).
           05  PPV-BAIRRO-X                   PIC X(040).
           05  PPV-CEP-X                      PIC X(008).
           05  PPV-COMPL-X                    PIC X(040).
           05  PPV-CPF-CNPJ-X                 PIC X(011).
           05  PPV-DT-INCL-X                  PIC X(010).
           05  PPV-DT-OFICIO-X                PIC X(010).
           05  PPV-FILLER1-X                  PIC X(020).
           05  PPV-FILLER2-X                  PIC X(020).
           05  PPV-HR-INCL-X                  PIC X(006).
           05  PPV-ID-PROV-X                  PIC X(030).
           05  PPV-INQUERITO-X                PIC X(030).
           05  PPV-JUIZO-X                    PIC X(030).
           05  PPV-LOGRAD-X                   PIC X(030).
           05  PPV-MUN-X                      PIC X(030).
           05  PPV-NRO-X                      PIC X(030).
           05  PPV-PLACA-MERC-X               PIC X(010).
           05  PPV-PLACA-X                    PIC X(010).
           05  PPV-PROCESSO-X                 PIC X(010).
           05  PPV-PROPR-PROV-X               PIC X(030).
           05  PPV-PROTOCOLO-X                PIC X(010).
           05  PPV-TIPO-PROV-X                PIC X(006).
           05  PPV-USUARIO-X                  PIC X(008).
           05  PPV-BAIRRO                     PIC X(040).
           05  PPV-CEP                        PIC X(008).
           05  PPV-COMPL                      PIC X(040).
           05  PPV-CPF-CNPJ                   PIC X(011).
           05  PPV-DT-INCL                    PIC 9(009).
           05  PPV-DT-OFICIO                  PIC 9(009).
           05  PPV-FILLER1                    PIC X(020).
           05  PPV-FILLER2                    PIC X(020).
           05  PPV-HR-INCL                    PIC 9(009).
           05  PPV-ID-PROV                    PIC X(030).
           05  PPV-INQUERITO                  PIC X(030).
           05  PPV-JUIZO                      PIC X(030).
           05  PPV-LOGRAD                     PIC X(030).
           05  PPV-MUN                        PIC X(030).
           05  PPV-NRO                        PIC X(030).
           05  PPV-PLACA-MERC                 PIC X(010).
           05  PPV-PLACA                      PIC X(010).
           05  PPV-PROCESSO                   PIC X(010).
           05  PPV-PROPR-PROV                 PIC X(030).
           05  PPV-PROTOCOLO                  PIC X(010).
           05  PPV-TIPO-PROV                  PIC X(006).
           05  PPV-USUARIO                    PIC X(008).
