      * WSD copybook for GEVEXCLUIDODS (auto-generated)
       01  GEVEXCLUIDODS.
           05  GEVEXCLUIDODS-ROWID            PIC X(018).
           05  GEX-ANO-X                      PIC X(004).
           05  GEX-ANOFABR-X                  PIC X(004).
           05  GEX-ANOMOD-X                   PIC X(004).
           05  GEX-ARREND-FIN-X               PIC X(030).
           05  GEX-AUT-DIGITAL-X              PIC X(030).
           05  GEX-AUT-EMPL-X                 PIC X(030).
           05  GEX-BAIRRO-X                   PIC X(040).
           05  GEX-CAP-CAR-X                  PIC X(030).
           05  GEX-CAP-PAS-X                  PIC X(030).
           05  GEX-CARROCERIA-X               PIC X(030).
           05  GEX-CATEGORIA-X                PIC X(006).
           05  GEX-CEP-ENDPROP-X              PIC X(008).
           05  GEX-CHASSI-REM-X               PIC X(021).
           05  GEX-CHASSI-X                   PIC X(021).
           05  GEX-CHAVEACESS-NF-X            PIC X(030).
           05  GEX-CILINDRADA-X               PIC X(030).
           05  GEX-CMT-X                      PIC X(030).
           05  GEX-COMBUSTIVEL-X              PIC X(006).
           05  GEX-COMODATO-X                 PIC X(030).
           05  GEX-COMPL-X                    PIC X(040).
           05  GEX-COMTROP5-EXCL-X            PIC X(030).
           05  GEX-CONFERENTE-X               PIC X(030).
           05  GEX-COR-X                      PIC X(030).
           05  GEX-CPF-USUSTAT-X              PIC X(011).
           05  GEX-CPFCGC-X                   PIC X(014).
           05  GEX-DATA-VENDA-X               PIC X(010).
           05  GEX-DESP-SSP-X                 PIC X(030).
           05  GEX-DIGITADOR-X                PIC X(030).
           05  GEX-DT-ALTERACAO-X             PIC X(010).
           05  GEX-DT-CONFERENTE-X            PIC X(010).
           05  GEX-DT-DIGITADOR-X             PIC X(010).
           05  GEX-DT-EMIS-NF-X               PIC X(010).
           05  GEX-DT-EXCLUSAO-X              PIC X(010).
           05  GEX-DT-INCLUSAO-X              PIC X(010).
           05  GEX-DT-REC-DOCTS-X             PIC X(010).
           05  GEX-DT-STAT-ECRV-X             PIC X(010).
           05  GEX-DT-VIG-CONTR-X             PIC X(010).
           05  GEX-DT-VIST-X                  PIC X(010).
           05  GEX-ENDERECO-X                 PIC X(040).
           05  GEX-ESPECIE-X                  PIC X(006).
           05  GEX-ESPELHO-ANT-X              PIC X(030).
           05  GEX-FILLER1-X                  PIC X(020).
           05  GEX-FILLER2-X                  PIC X(020).
           05  GEX-FILLER3-X                  PIC X(020).
           05  GEX-FILLER4-X                  PIC X(020).
           05  GEX-FILLER5-X                  PIC X(020).
           05  GEX-FINANC-X                   PIC X(030).
           05  GEX-HR-ALTERACAO-X             PIC X(006).
           05  GEX-HR-EXCLUSAO-X              PIC X(006).
           05  GEX-HR-INCLUSAO-X              PIC X(006).
           05  GEX-HR-STAT-ECRV-X             PIC X(006).
           05  GEX-ID-CONTR-X                 PIC X(030).
           05  GEX-ID-PRESTADORA-X            PIC X(030).
           05  GEX-IN-TROCA-MERC-X            PIC X(030).
           05  GEX-IND-RENAVE-X               PIC X(030).
           05  GEX-LETRA-ANT-X                PIC X(030).
           05  GEX-LOC-IMPR-X                 PIC X(030).
           05  GEX-MARCA-X                    PIC X(006).
           05  GEX-MOTSOL-FICHA-X             PIC X(030).
           05  GEX-MUNIC-ANT-X                PIC X(005).
           05  GEX-MUNIC-IMOVEL-X             PIC X(005).
           05  GEX-MUNIC-PLACA-X              PIC X(010).
           05  GEX-NOME-PROPR-X               PIC X(040).
           05  GEX-NOMEPROPR-ANT-X            PIC X(040).
           05  GEX-NRO-CAMBIO-X               PIC X(030).
           05  GEX-NRO-CONTRATO-X             PIC X(010).
           05  GEX-NRO-EIXOS-X                PIC X(030).
           05  GEX-NRO-ESPELHO-X              PIC X(030).
           05  GEX-NRO-FICHA-X                PIC X(030).
           05  GEX-NRO-FISCAL-X               PIC X(030).
           05  GEX-NRO-IMOVEL-X               PIC X(030).
           05  GEX-NRO-MOTOR-X                PIC X(030).
           05  GEX-NUMERO1-ANT-X              PIC X(030).
           05  GEX-NUMERO2-ANT-X              PIC X(030).
           05  GEX-OPCAO-X                    PIC X(030).
           05  GEX-ORG-RG-X                   PIC X(030).
           05  GEX-PBT-X                      PIC X(030).
           05  GEX-PLA-ANT-MERC-X             PIC X(030).
           05  GEX-PLACA-MERC-X               PIC X(010).
           05  GEX-PLACA-X                    PIC X(010).
           05  GEX-POTENCIA-X                 PIC X(030).
           05  GEX-PROCEDENCIA-X              PIC X(030).
           05  GEX-PROT-REM-X                 PIC X(030).
           05  GEX-RENAVAM-X                  PIC X(011).
           05  GEX-RESTR-FINANC-X             PIC X(030).
           05  GEX-RET-BIN-X                  PIC X(030).
           05  GEX-RET-CONSIST-X              PIC X(030).
           05  GEX-RG-X                       PIC X(030).
           05  GEX-SEQ-TRANSACAO-X            PIC X(010).
           05  GEX-STATUS-ECRV-X              PIC X(020).
           05  GEX-STATUS-REG-X               PIC X(020).
           05  GEX-TELEFONE-X                 PIC X(010).
           05  GEX-TIPO-X                     PIC X(006).
           05  GEX-TIPSOL-PLACA-X             PIC X(010).
           05  GEX-TP-VEIC-OFIC-X             PIC X(010).
           05  GEX-TRANS-EXCL-X               PIC X(030).
           05  GEX-TRANSACAO-X                PIC X(030).
           05  GEX-UF-ESP-ANT-X               PIC X(002).
           05  GEX-UF-PLACA-ANT-X             PIC X(010).
           05  GEX-UF-X                       PIC X(002).
           05  GEX-VALOR-NFISCAL-X            PIC X(030).
           05  GEX-VISTORIADOR-X              PIC X(030).
           05  GEX-ANO                        PIC 9(009).
           05  GEX-ANOFABR                    PIC 9(009).
           05  GEX-ANOMOD                     PIC 9(009).
           05  GEX-ARREND-FIN                 PIC X(030).
           05  GEX-AUT-DIGITAL                PIC X(030).
           05  GEX-AUT-EMPL                   PIC X(030).
           05  GEX-BAIRRO                     PIC X(040).
           05  GEX-CAP-CAR                    PIC X(030).
           05  GEX-CAP-PAS                    PIC X(030).
           05  GEX-CARROCERIA                 PIC X(030).
           05  GEX-CATEGORIA                  PIC X(006).
           05  GEX-CEP-ENDPROP                PIC X(008).
           05  GEX-CHASSI-REM                 PIC X(021).
           05  GEX-CHASSI                     PIC X(021).
           05  GEX-CHAVEACESS-NF              PIC X(030).
           05  GEX-CILINDRADA                 PIC X(030).
           05  GEX-CMT                        PIC X(030).
           05  GEX-COMBUSTIVEL                PIC X(006).
           05  GEX-COMODATO                   PIC X(030).
           05  GEX-COMPL                      PIC X(040).
           05  GEX-COMTROP5-EXCL              PIC X(030).
           05  GEX-CONFERENTE                 PIC X(030).
           05  GEX-COR                        PIC X(030).
           05  GEX-CPF-USUSTAT                PIC X(011).
           05  GEX-CPFCGC                     PIC X(014).
           05  GEX-DATA-VENDA                 PIC X(010).
           05  GEX-DESP-SSP                   PIC X(030).
           05  GEX-DIGITADOR                  PIC X(030).
           05  GEX-DT-ALTERACAO               PIC 9(009).
           05  GEX-DT-CONFERENTE              PIC 9(009).
           05  GEX-DT-DIGITADOR               PIC 9(009).
           05  GEX-DT-EMIS-NF                 PIC 9(009).
           05  GEX-DT-EXCLUSAO                PIC 9(009).
           05  GEX-DT-INCLUSAO                PIC 9(009).
           05  GEX-DT-REC-DOCTS               PIC 9(009).
           05  GEX-DT-STAT-ECRV               PIC 9(009).
           05  GEX-DT-VIG-CONTR               PIC 9(009).
           05  GEX-DT-VIST                    PIC 9(009).
           05  GEX-ENDERECO                   PIC X(040).
           05  GEX-ESPECIE                    PIC X(006).
           05  GEX-ESPELHO-ANT                PIC X(030).
           05  GEX-FILLER1                    PIC X(020).
           05  GEX-FILLER2                    PIC X(020).
           05  GEX-FILLER3                    PIC X(020).
           05  GEX-FILLER4                    PIC X(020).
           05  GEX-FILLER5                    PIC X(020).
           05  GEX-FINANC                     PIC X(030).
           05  GEX-HR-ALTERACAO               PIC 9(009).
           05  GEX-HR-EXCLUSAO                PIC 9(009).
           05  GEX-HR-INCLUSAO                PIC 9(009).
           05  GEX-HR-STAT-ECRV               PIC 9(009).
           05  GEX-ID-CONTR                   PIC X(030).
           05  GEX-ID-PRESTADORA              PIC X(030).
           05  GEX-IN-TROCA-MERC              PIC X(030).
           05  GEX-IND-RENAVE                 PIC X(030).
           05  GEX-LETRA-ANT                  PIC X(030).
           05  GEX-LOC-IMPR                   PIC X(030).
           05  GEX-MARCA                      PIC X(006).
           05  GEX-MOTSOL-FICHA               PIC X(030).
           05  GEX-MUNIC-ANT                  PIC X(005).
           05  GEX-MUNIC-IMOVEL               PIC X(005).
           05  GEX-MUNIC-PLACA                PIC X(010).
           05  GEX-NOME-PROPR                 PIC X(040).
           05  GEX-NOMEPROPR-ANT              PIC X(040).
           05  GEX-NRO-CAMBIO                 PIC X(030).
           05  GEX-NRO-CONTRATO               PIC X(010).
           05  GEX-NRO-EIXOS                  PIC X(030).
           05  GEX-NRO-ESPELHO                PIC X(030).
           05  GEX-NRO-FICHA                  PIC X(030).
           05  GEX-NRO-FISCAL                 PIC X(030).
           05  GEX-NRO-IMOVEL                 PIC X(030).
           05  GEX-NRO-MOTOR                  PIC X(030).
           05  GEX-NUMERO1-ANT                PIC X(030).
           05  GEX-NUMERO2-ANT                PIC X(030).
           05  GEX-OPCAO                      PIC X(030).
           05  GEX-ORG-RG                     PIC X(030).
           05  GEX-PBT                        PIC X(030).
           05  GEX-PLA-ANT-MERC               PIC X(030).
           05  GEX-PLACA-MERC                 PIC X(010).
           05  GEX-PLACA                      PIC X(010).
           05  GEX-POTENCIA                   PIC X(030).
           05  GEX-PROCEDENCIA                PIC X(030).
           05  GEX-PROT-REM                   PIC X(030).
           05  GEX-RENAVAM                    PIC X(011).
           05  GEX-RESTR-FINANC               PIC X(030).
           05  GEX-RET-BIN                    PIC X(030).
           05  GEX-RET-CONSIST                PIC X(030).
           05  GEX-RG                         PIC X(030).
           05  GEX-SEQ-TRANSACAO              PIC 9(009).
           05  GEX-STATUS-ECRV                PIC X(020).
           05  GEX-STATUS-REG                 PIC X(020).
           05  GEX-TELEFONE                   PIC X(010).
           05  GEX-TIPO                       PIC X(006).
           05  GEX-TIPSOL-PLACA               PIC X(010).
           05  GEX-TP-VEIC-OFIC               PIC X(010).
           05  GEX-TRANS-EXCL                 PIC X(030).
           05  GEX-TRANSACAO                  PIC X(030).
           05  GEX-UF-ESP-ANT                 PIC X(002).
           05  GEX-UF-PLACA-ANT               PIC X(010).
           05  GEX-UF                         PIC X(002).
           05  GEX-VALOR-NFISCAL              PIC X(030).
           05  GEX-VISTORIADOR                PIC X(030).
