      * WSD copybook for TAXASDS (auto-generated)
       01  TAXASDS.
           05  TAXASDS-ROWID                  PIC X(018).
           05  TAV-COD-SERVICO-X              PIC X(006).
           05  TAV-CPF-CGC-X                  PIC X(014).
           05  TAV-DESP-SSP-X                 PIC X(030).
           05  TAV-DT-INCLUSAO-X              PIC X(010).
           05  TAV-DT-VALID-F-X               PIC X(010).
           05  TAV-DT-VALID-X                 PIC X(010).
           05  TAV-FILLER1-X                  PIC X(020).
           05  TAV-FILLER2-X                  PIC X(020).
           05  TAV-HR-INCLUSAO-X              PIC X(006).
           05  TAV-HR-VALID-F-X               PIC X(006).
           05  TAV-HR-VALID-X                 PIC X(006).
           05  TAV-ID-FIM-X                   PIC X(030).
           05  TAV-ID-PIX-X                   PIC X(030).
           05  TAV-MUNICIPIO-X                PIC X(005).
           05  TAV-PLACA-MERC-X               PIC X(010).
           05  TAV-PROTOCOLO-F-X              PIC X(010).
           05  TAV-RENAVAM-X                  PIC X(011).
           05  TAV-SENHA-SEFAZ-X              PIC X(030).
           05  TAV-SENHA-X                    PIC X(030).
           05  TAV-SITUACAO-X                 PIC X(020).
           05  TAV-TRANSACAO-F-X              PIC X(030).
           05  TAV-TRANSACAO-X                PIC X(030).
           05  TAV-USUARIO-F-X                PIC X(008).
           05  TAV-USUARIO-X                  PIC X(008).
           05  TAV-COD-SERVICO                PIC 9(009).
           05  TAV-CPF-CGC                    PIC X(014).
           05  TAV-DESP-SSP                   PIC X(030).
           05  TAV-DT-INCLUSAO                PIC 9(009).
           05  TAV-DT-VALID-F                 PIC 9(009).
           05  TAV-DT-VALID                   PIC 9(009).
           05  TAV-FILLER1                    PIC X(020).
           05  TAV-FILLER2                    PIC X(020).
           05  TAV-HR-INCLUSAO                PIC 9(009).
           05  TAV-HR-VALID-F                 PIC 9(009).
           05  TAV-HR-VALID                   PIC 9(009).
           05  TAV-ID-FIM                     PIC X(030).
           05  TAV-ID-PIX                     PIC X(030).
           05  TAV-MUNICIPIO                  PIC 9(009).
           05  TAV-PLACA-MERC                 PIC X(010).
           05  TAV-PROTOCOLO-F                PIC X(010).
           05  TAV-RENAVAM                    PIC X(011).
           05  TAV-SENHA-SEFAZ                PIC X(030).
           05  TAV-SENHA                      PIC X(030).
           05  TAV-SITUACAO                   PIC X(020).
           05  TAV-TRANSACAO-F                PIC X(030).
           05  TAV-TRANSACAO                  PIC X(030).
           05  TAV-USUARIO-F                  PIC X(008).
           05  TAV-USUARIO                    PIC X(008).
