      * WSD copybook for COMVENDS (auto-generated)
       01  COMVENDS.
           05  COMVENDS-ROWID                 PIC X(018).
           05  CVV-ANO-FABR-X                 PIC X(004).
           05  CVV-ANO-MOD-X                  PIC X(004).
           05  CVV-ANO-X                      PIC X(004).
           05  CVV-BAIRRO-CART-X              PIC X(040).
           05  CVV-BAIRRO-CARTC-X             PIC X(040).
           05  CVV-BAIRRO-CV-X                PIC X(040).
           05  CVV-CD-SEG-CRV-X               PIC X(006).
           05  CVV-CEP-END-CART-X             PIC X(008).
           05  CVV-CEP-END-CARTC-X            PIC X(008).
           05  CVV-CEP-END-CV-X               PIC X(008).
           05  CVV-CHASSI-X                   PIC X(021).
           05  CVV-CNPJ-SEG-X                 PIC X(014).
           05  CVV-COMP-END-CART-X            PIC X(030).
           05  CVV-COMPEND-CARTC-X            PIC X(030).
           05  CVV-COMPL-CV-X                 PIC X(040).
           05  CVV-CPF-CGC-CV-X               PIC X(014).
           05  CVV-CPF-USUPROT-X              PIC X(011).
           05  CVV-DDD-CART-X                 PIC X(010).
           05  CVV-DDD-CARTC-X                PIC X(010).
           05  CVV-DOCTO-CV-X                 PIC X(030).
           05  CVV-DOCTO-INFORM-X             PIC X(030).
           05  CVV-DT-ATUALIZ-X               PIC X(010).
           05  CVV-DT-AVERBACAO-X             PIC X(010).
           05  CVV-DT-BIN-X                   PIC X(010).
           05  CVV-DT-CANC-X                  PIC X(010).
           05  CVV-DT-DOCTS-X                 PIC X(010).
           05  CVV-DT-EMIS-CRV-X              PIC X(010).
           05  CVV-DT-INCLUSAO-X              PIC X(010).
           05  CVV-DT-LEILAO-X                PIC X(010).
           05  CVV-DT-NFISCAL-X               PIC X(010).
           05  CVV-DT-PROT-X                  PIC X(010).
           05  CVV-DT-REC-FIRMA-X             PIC X(010).
           05  CVV-DT-VENDA-X                 PIC X(010).
           05  CVV-END-CART-X                 PIC X(030).
           05  CVV-END-CARTC-X                PIC X(030).
           05  CVV-ENDERECO-CV-X              PIC X(040).
           05  CVV-ENTR-DADOS-X               PIC X(030).
           05  CVV-FINANC-X                   PIC X(030).
           05  CVV-FOL-COMP-X                 PIC X(030).
           05  CVV-FOL-VEND-X                 PIC X(030).
           05  CVV-HR-CANC-X                  PIC X(006).
           05  CVV-HR-INCLUSAO-X              PIC X(006).
           05  CVV-ID-ASSINAT-X               PIC X(030).
           05  CVV-IDENT-CART-X               PIC X(030).
           05  CVV-IDENT-CARTC-X              PIC X(030).
           05  CVV-IDENT-PROPR-X              PIC X(030).
           05  CVV-LIV-COMP-X                 PIC X(030).
           05  CVV-LIV-VEND-X                 PIC X(030).
           05  CVV-MOT-CANC-X                 PIC X(030).
           05  CVV-MUN-END-CV-X               PIC X(005).
           05  CVV-MUN-VENDA-X                PIC X(005).
           05  CVV-MUNIC-CART-X               PIC X(005).
           05  CVV-MUNIC-CARTC-X              PIC X(005).
           05  CVV-MUNICIPIO-X                PIC X(005).
           05  CVV-NOME-CART-X                PIC X(040).
           05  CVV-NOME-CARTC-X               PIC X(040).
           05  CVV-NOME-CV-X                  PIC X(040).
           05  CVV-NOME-INFORM-X              PIC X(040).
           05  CVV-NOME-PROPR-X               PIC X(040).
           05  CVV-NRO-CRV-X                  PIC X(030).
           05  CVV-NRO-END-CART-X             PIC X(030).
           05  CVV-NRO-END-CARTC-X            PIC X(030).
           05  CVV-NRO-FICHA-X                PIC X(030).
           05  CVV-NRO-IDENT-CV-X             PIC X(030).
           05  CVV-NRO-IMOVEL-CV-X            PIC X(030).
           05  CVV-NRO-VIA-CRV-X              PIC X(030).
           05  CVV-PLACA-MERC-X               PIC X(010).
           05  CVV-PLACA-X                    PIC X(010).
           05  CVV-PROTOC-FAZ-X               PIC X(010).
           05  CVV-RENAVAM-X                  PIC X(011).
           05  CVV-RET-BIN-X                  PIC X(030).
           05  CVV-SSP-DESP-X                 PIC X(030).
           05  CVV-TEL-CART-X                 PIC X(030).
           05  CVV-TEL-CARTC-X                PIC X(030).
           05  CVV-TIPO-DOCTO-X               PIC X(006).
           05  CVV-TP-DOC-CART-X              PIC X(030).
           05  CVV-TP-DOC-CARTC-X             PIC X(030).
           05  CVV-UF-CART-X                  PIC X(002).
           05  CVV-UF-CARTC-X                 PIC X(002).
           05  CVV-UF-EMISSAO-X               PIC X(002).
           05  CVV-UF-IMOVEL-CV-X             PIC X(002).
           05  CVV-USU-PROT-X                 PIC X(008).
           05  CVV-USUARIO-X                  PIC X(008).
           05  CVV-ANO-FABR                   PIC 9(009).
           05  CVV-ANO-MOD                    PIC 9(009).
           05  CVV-ANO                        PIC 9(009).
           05  CVV-BAIRRO-CART                PIC X(040).
           05  CVV-BAIRRO-CARTC               PIC X(040).
           05  CVV-BAIRRO-CV                  PIC X(040).
           05  CVV-CD-SEG-CRV                 PIC X(006).
           05  CVV-CEP-END-CART               PIC X(008).
           05  CVV-CEP-END-CARTC              PIC X(008).
           05  CVV-CEP-END-CV                 PIC X(008).
           05  CVV-CHASSI                     PIC X(021).
           05  CVV-CNPJ-SEG                   PIC X(014).
           05  CVV-COMP-END-CART              PIC X(030).
           05  CVV-COMPEND-CARTC              PIC X(030).
           05  CVV-COMPL-CV                   PIC X(040).
           05  CVV-CPF-CGC-CV                 PIC X(014).
           05  CVV-CPF-USUPROT                PIC X(011).
           05  CVV-DDD-CART                   PIC X(010).
           05  CVV-DDD-CARTC                  PIC X(010).
           05  CVV-DOCTO-CV                   PIC X(030).
           05  CVV-DOCTO-INFORM               PIC X(030).
           05  CVV-DT-ATUALIZ                 PIC 9(009).
           05  CVV-DT-AVERBACAO               PIC 9(009).
           05  CVV-DT-BIN                     PIC 9(009).
           05  CVV-DT-CANC                    PIC 9(009).
           05  CVV-DT-DOCTS                   PIC 9(009).
           05  CVV-DT-EMIS-CRV                PIC 9(009).
           05  CVV-DT-INCLUSAO                PIC 9(009).
           05  CVV-DT-LEILAO                  PIC 9(009).
           05  CVV-DT-NFISCAL                 PIC 9(009).
           05  CVV-DT-PROT                    PIC 9(009).
           05  CVV-DT-REC-FIRMA               PIC 9(009).
           05  CVV-DT-VENDA                   PIC 9(009).
           05  CVV-END-CART                   PIC X(030).
           05  CVV-END-CARTC                  PIC X(030).
           05  CVV-ENDERECO-CV                PIC X(040).
           05  CVV-ENTR-DADOS                 PIC X(030).
           05  CVV-FINANC                     PIC X(030).
           05  CVV-FOL-COMP                   PIC X(030).
           05  CVV-FOL-VEND                   PIC X(030).
           05  CVV-HR-CANC                    PIC 9(009).
           05  CVV-HR-INCLUSAO                PIC 9(009).
           05  CVV-ID-ASSINAT                 PIC X(030).
           05  CVV-IDENT-CART                 PIC X(030).
           05  CVV-IDENT-CARTC                PIC X(030).
           05  CVV-IDENT-PROPR                PIC X(030).
           05  CVV-LIV-COMP                   PIC X(030).
           05  CVV-LIV-VEND                   PIC X(030).
           05  CVV-MOT-CANC                   PIC X(030).
           05  CVV-MUN-END-CV                 PIC X(005).
           05  CVV-MUN-VENDA                  PIC X(005).
           05  CVV-MUNIC-CART                 PIC X(005).
           05  CVV-MUNIC-CARTC                PIC X(005).
           05  CVV-MUNICIPIO                  PIC 9(009).
           05  CVV-NOME-CART                  PIC X(040).
           05  CVV-NOME-CARTC                 PIC X(040).
           05  CVV-NOME-CV                    PIC X(040).
           05  CVV-NOME-INFORM                PIC X(040).
           05  CVV-NOME-PROPR                 PIC X(040).
           05  CVV-NRO-CRV                    PIC X(030).
           05  CVV-NRO-END-CART               PIC X(030).
           05  CVV-NRO-END-CARTC              PIC X(030).
           05  CVV-NRO-FICHA                  PIC X(030).
           05  CVV-NRO-IDENT-CV               PIC X(030).
           05  CVV-NRO-IMOVEL-CV              PIC X(030).
           05  CVV-NRO-VIA-CRV                PIC X(030).
           05  CVV-PLACA-MERC                 PIC X(010).
           05  CVV-PLACA                      PIC X(010).
           05  CVV-PROTOC-FAZ                 PIC X(010).
           05  CVV-RENAVAM                    PIC X(011).
           05  CVV-RET-BIN                    PIC X(030).
           05  CVV-SSP-DESP                   PIC X(030).
           05  CVV-TEL-CART                   PIC X(030).
           05  CVV-TEL-CARTC                  PIC X(030).
           05  CVV-TIPO-DOCTO                 PIC X(006).
           05  CVV-TP-DOC-CART                PIC X(030).
           05  CVV-TP-DOC-CARTC               PIC X(030).
           05  CVV-UF-CART                    PIC X(002).
           05  CVV-UF-CARTC                   PIC X(002).
           05  CVV-UF-EMISSAO                 PIC X(002).
           05  CVV-UF-IMOVEL-CV               PIC X(002).
           05  CVV-USU-PROT                   PIC X(008).
           05  CVV-USUARIO                    PIC X(008).
