      * WSD copybook for MOTORDS (auto-generated)
       01  MOTORDS.
           05  MOTORDS-ROWID                  PIC X(018).
           05  MTR-CHASSI-X                   PIC X(021).
           05  MTR-DT-EXCLUSAO-X              PIC X(010).
           05  MTR-DT-INCLUSAO-X              PIC X(010).
           05  MTR-DT-PROT-X                  PIC X(010).
           05  MTR-DT-UTIL-X                  PIC X(010).
           05  MTR-FILLER2-X                  PIC X(020).
           05  MTR-GERADO-X                   PIC X(030).
           05  MTR-HR-EXCLUSAO-X              PIC X(006).
           05  MTR-HR-INCLUSAO-X              PIC X(006).
           05  MTR-HR-UTIL-X                  PIC X(006).
           05  MTR-MUNIC-UTIL-X               PIC X(005).
           05  MTR-NUM-MOTOR-X                PIC X(010).
           05  MTR-PLACA-MERC-X               PIC X(010).
           05  MTR-PLACA-X                    PIC X(010).
           05  MTR-PROTOCOLO-X                PIC X(010).
           05  MTR-REMARCADO-X                PIC X(006).
           05  MTR-SIT-X                      PIC X(030).
           05  MTR-TRANSA-UTIL-X              PIC X(030).
           05  MTR-USU-EXCL-X                 PIC X(008).
           05  MTR-USU-UTIL-X                 PIC X(008).
           05  MTR-USUARIO-X                  PIC X(008).
           05  MTR-CHASSI                     PIC X(021).
           05  MTR-DT-EXCLUSAO                PIC 9(009).
           05  MTR-DT-INCLUSAO                PIC 9(009).
           05  MTR-DT-PROT                    PIC 9(009).
           05  MTR-DT-UTIL                    PIC 9(009).
           05  MTR-FILLER2                    PIC X(020).
           05  MTR-GERADO                     PIC X(030).
           05  MTR-HR-EXCLUSAO                PIC 9(009).
           05  MTR-HR-INCLUSAO                PIC 9(009).
           05  MTR-HR-UTIL                    PIC 9(009).
           05  MTR-MUNIC-UTIL                 PIC X(005).
           05  MTR-NUM-MOTOR                  PIC 9(009).
           05  MTR-PLACA-MERC                 PIC X(010).
           05  MTR-PLACA                      PIC X(010).
           05  MTR-PROTOCOLO                  PIC X(010).
           05  MTR-REMARCADO                  PIC X(006).
           05  MTR-SIT                        PIC X(030).
           05  MTR-TRANSA-UTIL                PIC X(030).
           05  MTR-USU-EXCL                   PIC X(008).
           05  MTR-USU-UTIL                   PIC X(008).
           05  MTR-USUARIO                    PIC X(008).
