      * WSD copybook for SIRCOFDS (auto-generated)
       01  SIRCOFDS.
           05  SIRCOFDS-ROWID                 PIC X(018).
           05  SIR-ANOFABR-X                  PIC X(004).
           05  SIR-ANOMOD-X                   PIC X(004).
           05  SIR-ASSINELET-X                PIC X(030).
           05  SIR-BAIRRO-CRED-X              PIC X(040).
           05  SIR-BAIRRO-DEVED-X             PIC X(040).
           05  SIR-CD-AGENTE-X                PIC X(006).
           05  SIR-CEP-CRED-X                 PIC X(008).
           05  SIR-CEP-DEVED-X                PIC X(008).
           05  SIR-CHASSI-REM-X               PIC X(021).
           05  SIR-CHASSI-X                   PIC X(021).
           05  SIR-CNPJ-AGENTE-X              PIC X(014).
           05  SIR-COMISSAO-X                 PIC X(030).
           05  SIR-COMPLEM-CRED-X             PIC X(040).
           05  SIR-COMPLEM-DEVED-X            PIC X(040).
           05  SIR-CPF-CGC-DEVED-X            PIC X(014).
           05  SIR-DDD-CRED-X                 PIC X(010).
           05  SIR-DDD-DEVED-X                PIC X(010).
           05  SIR-DT-ADITCONTR-X             PIC X(010).
           05  SIR-DT-CANCELA-X               PIC X(010).
           05  SIR-DT-INCLUSAO-X              PIC X(010).
           05  SIR-DT-LIBERCRED-X             PIC X(010).
           05  SIR-DT-QUITACAO-X              PIC X(010).
           05  SIR-DT-VENCPAR1-X              PIC X(010).
           05  SIR-DT-VENCULTPAR-X            PIC X(010).
           05  SIR-DT-VIG-CONTR-X             PIC X(010).
           05  SIR-FLAG-CANC-X                PIC X(030).
           05  SIR-FLAG-X                     PIC X(030).
           05  SIR-GR-CONSORCIO-X             PIC X(030).
           05  SIR-HR-INCLUSAO-X              PIC X(006).
           05  SIR-INDIC-COMIS-X              PIC X(030).
           05  SIR-INDIC-PENALID-X            PIC X(030).
           05  SIR-INDICES-X                  PIC X(030).
           05  SIR-IOF-X                      PIC X(030).
           05  SIR-LOGRAD-CRED-X              PIC X(030).
           05  SIR-LOGRAD-DEVED-X             PIC X(030).
           05  SIR-MUN-LIBERCRED-X            PIC X(005).
           05  SIR-MUNICIP-CRED-X             PIC X(005).
           05  SIR-MUNICIP-DEVED-X            PIC X(005).
           05  SIR-NOME-AGENTE-X              PIC X(040).
           05  SIR-NOME-DEVED-X               PIC X(040).
           05  SIR-NUM-ADITCONTR-X            PIC X(010).
           05  SIR-NUM-CONTR-X                PIC X(010).
           05  SIR-NUM-COTACONSO-X            PIC X(010).
           05  SIR-NUM-REGIADIT-X             PIC X(010).
           05  SIR-NUM-REGICONTR-X            PIC X(010).
           05  SIR-NUM-RESTRICAO-X            PIC X(010).
           05  SIR-NUMIMOV-CRED-X             PIC X(030).
           05  SIR-NUMIMOV-DEVED-X            PIC X(030).
           05  SIR-OPERADORA-X                PIC X(030).
           05  SIR-PENALID-X                  PIC X(030).
           05  SIR-PLACA-MERC-X               PIC X(010).
           05  SIR-PLACA-X                    PIC X(010).
           05  SIR-QTD-PARC-X                 PIC X(010).
           05  SIR-RENAVAM-X                  PIC X(011).
           05  SIR-TAXA-CONTRATO-X            PIC X(010).
           05  SIR-TAXA-JUROANO-X             PIC X(030).
           05  SIR-TAXA-JUROMES-X             PIC X(030).
           05  SIR-TEL-CRED-X                 PIC X(030).
           05  SIR-TEL-DEVED-X                PIC X(030).
           05  SIR-TIPO-RESTR-X               PIC X(006).
           05  SIR-TOTAL-FINANC-X             PIC X(030).
           05  SIR-TRAN-QUITACAO-X            PIC X(030).
           05  SIR-TRANS-CANCELA-X            PIC X(030).
           05  SIR-TRANS-GRAVAME-X            PIC X(030).
           05  SIR-TX-MORA-X                  PIC X(030).
           05  SIR-TX-MULTA-X                 PIC X(030).
           05  SIR-UF-CRED-X                  PIC X(002).
           05  SIR-UF-DEVED-X                 PIC X(002).
           05  SIR-UF-LIBERCRED-X             PIC X(002).
           05  SIR-UFPLACA-X                  PIC X(010).
           05  SIR-VALOR-MORA-X               PIC X(030).
           05  SIR-VALOR-MULTA-X              PIC X(030).
           05  SIR-VALOR-PAR-X                PIC X(030).
           05  SIR-ANOFABR                    PIC 9(009).
           05  SIR-ANOMOD                     PIC 9(009).
           05  SIR-ASSINELET                  PIC X(030).
           05  SIR-BAIRRO-CRED                PIC X(040).
           05  SIR-BAIRRO-DEVED               PIC X(040).
           05  SIR-CD-AGENTE                  PIC X(006).
           05  SIR-CEP-CRED                   PIC X(008).
           05  SIR-CEP-DEVED                  PIC X(008).
           05  SIR-CHASSI-REM                 PIC X(021).
           05  SIR-CHASSI                     PIC X(021).
           05  SIR-CNPJ-AGENTE                PIC X(014).
           05  SIR-COMISSAO                   PIC X(030).
           05  SIR-COMPLEM-CRED               PIC X(040).
           05  SIR-COMPLEM-DEVED              PIC X(040).
           05  SIR-CPF-CGC-DEVED              PIC X(014).
           05  SIR-DDD-CRED                   PIC X(010).
           05  SIR-DDD-DEVED                  PIC X(010).
           05  SIR-DT-ADITCONTR               PIC 9(009).
           05  SIR-DT-CANCELA                 PIC 9(009).
           05  SIR-DT-INCLUSAO                PIC 9(009).
           05  SIR-DT-LIBERCRED               PIC 9(009).
           05  SIR-DT-QUITACAO                PIC 9(009).
           05  SIR-DT-VENCPAR1                PIC 9(009).
           05  SIR-DT-VENCULTPAR              PIC 9(009).
           05  SIR-DT-VIG-CONTR               PIC 9(009).
           05  SIR-FLAG-CANC                  PIC X(030).
           05  SIR-FLAG                       PIC X(030).
           05  SIR-GR-CONSORCIO               PIC X(030).
           05  SIR-HR-INCLUSAO                PIC 9(009).
           05  SIR-INDIC-COMIS                PIC X(030).
           05  SIR-INDIC-PENALID              PIC X(030).
           05  SIR-INDICES                    PIC X(030).
           05  SIR-IOF                        PIC X(030).
           05  SIR-LOGRAD-CRED                PIC X(030).
           05  SIR-LOGRAD-DEVED               PIC X(030).
           05  SIR-MUN-LIBERCRED              PIC X(005).
           05  SIR-MUNICIP-CRED               PIC X(005).
           05  SIR-MUNICIP-DEVED              PIC X(005).
           05  SIR-NOME-AGENTE                PIC X(040).
           05  SIR-NOME-DEVED                 PIC X(040).
           05  SIR-NUM-ADITCONTR              PIC 9(009).
           05  SIR-NUM-CONTR                  PIC 9(009).
           05  SIR-NUM-COTACONSO              PIC 9(009).
           05  SIR-NUM-REGIADIT               PIC 9(009).
           05  SIR-NUM-REGICONTR              PIC 9(009).
           05  SIR-NUM-RESTRICAO              PIC 9(009).
           05  SIR-NUMIMOV-CRED               PIC X(030).
           05  SIR-NUMIMOV-DEVED              PIC X(030).
           05  SIR-OPERADORA                  PIC X(030).
           05  SIR-PENALID                    PIC X(030).
           05  SIR-PLACA-MERC                 PIC X(010).
           05  SIR-PLACA                      PIC X(010).
           05  SIR-QTD-PARC                   PIC 9(009).
           05  SIR-RENAVAM                    PIC X(011).
           05  SIR-TAXA-CONTRATO              PIC X(010).
           05  SIR-TAXA-JUROANO               PIC X(030).
           05  SIR-TAXA-JUROMES               PIC X(030).
           05  SIR-TEL-CRED                   PIC X(030).
           05  SIR-TEL-DEVED                  PIC X(030).
           05  SIR-TIPO-RESTR                 PIC X(006).
           05  SIR-TOTAL-FINANC               PIC X(030).
           05  SIR-TRAN-QUITACAO              PIC X(030).
           05  SIR-TRANS-CANCELA              PIC X(030).
           05  SIR-TRANS-GRAVAME              PIC X(030).
           05  SIR-TX-MORA                    PIC X(030).
           05  SIR-TX-MULTA                   PIC X(030).
           05  SIR-UF-CRED                    PIC X(002).
           05  SIR-UF-DEVED                   PIC X(002).
           05  SIR-UF-LIBERCRED               PIC X(002).
           05  SIR-UFPLACA                    PIC X(010).
           05  SIR-VALOR-MORA                 PIC X(030).
           05  SIR-VALOR-MULTA                PIC X(030).
           05  SIR-VALOR-PAR                  PIC X(030).
