      * WSD copybook for INSPECAODS (auto-generated)
       01  INSPECAODS.
           05  INSPECAODS-ROWID               PIC X(018).
           05  INS-ANO-X                      PIC X(004).
           05  INS-ANOFABR-X                  PIC X(004).
           05  INS-CERTIFICACAO-X             PIC X(030).
           05  INS-COMBUS-X                   PIC X(006).
           05  INS-DT-INCL-X                  PIC X(010).
           05  INS-DT-INSPECAO-X              PIC X(010).
           05  INS-FILLER1-X                  PIC X(020).
           05  INS-FILLER2-X                  PIC X(020).
           05  INS-FILLER3-X                  PIC X(020).
           05  INS-HR-INCL-X                  PIC X(006).
           05  INS-HR-INSPECAO-X              PIC X(006).
           05  INS-LOCAL-X                    PIC X(030).
           05  INS-MUNICIPIO-X                PIC X(005).
           05  INS-OPERADORA-X                PIC X(030).
           05  INS-PLACA-MERC-X               PIC X(010).
           05  INS-PLACA-X                    PIC X(010).
           05  INS-RENAVAM-X                  PIC X(011).
           05  INS-TIPO-X                     PIC X(006).
           05  INS-ANO                        PIC 9(009).
           05  INS-ANOFABR                    PIC 9(009).
           05  INS-CERTIFICACAO               PIC X(030).
           05  INS-COMBUS                     PIC X(006).
           05  INS-DT-INCL                    PIC 9(009).
           05  INS-DT-INSPECAO                PIC 9(009).
           05  INS-FILLER1                    PIC X(020).
           05  INS-FILLER2                    PIC X(020).
           05  INS-FILLER3                    PIC X(020).
           05  INS-HR-INCL                    PIC 9(009).
           05  INS-HR-INSPECAO                PIC 9(009).
           05  INS-LOCAL                      PIC X(030).
           05  INS-MUNICIPIO                  PIC 9(009).
           05  INS-OPERADORA                  PIC X(030).
           05  INS-PLACA-MERC                 PIC X(010).
           05  INS-PLACA                      PIC X(010).
           05  INS-RENAVAM                    PIC X(011).
           05  INS-TIPO                       PIC X(006).
