      * WSD copybook for BLOQUEIODS (auto-generated)
       01  BLOQUEIODS.
           05  BLOQUEIODS-ROWID               PIC X(018).
           05  BLO-ANO-OFIC-X                 PIC X(004).
           05  BLO-ANO-PROCESSO-X             PIC X(004).
           05  BLO-ANO-PROTOC-X               PIC X(004).
           05  BLO-AUTORIDADE-X               PIC X(030).
           05  BLO-CD-ORG-BLOQ-X              PIC X(006).
           05  BLO-CHASSIS-X                  PIC X(021).
           05  BLO-DT-INCLUSAO-X              PIC X(010).
           05  BLO-FILLER-X                   PIC X(020).
           05  BLO-FILLER1-X                  PIC X(020).
           05  BLO-FILLER2-X                  PIC X(020).
           05  BLO-HR-INCLUSAO-X              PIC X(006).
           05  BLO-MUNIC-LEILAO-X             PIC X(005).
           05  BLO-MUNICIPIO-X                PIC X(005).
           05  BLO-NUM-OFIC-X                 PIC X(010).
           05  BLO-NUM-PROCESSO-X             PIC X(010).
           05  BLO-NUM-PROTOC-X               PIC X(010).
           05  BLO-PLACA-MERC-X               PIC X(010).
           05  BLO-PLACA-X                    PIC X(010).
           05  BLO-TIP-BLOQ-X                 PIC X(006).
           05  BLO-USUARIO-X                  PIC X(008).
           05  BLO-ANO-OFIC                   PIC 9(009).
           05  BLO-ANO-PROCESSO               PIC 9(009).
           05  BLO-ANO-PROTOC                 PIC 9(009).
           05  BLO-AUTORIDADE                 PIC X(030).
           05  BLO-CD-ORG-BLOQ                PIC X(006).
           05  BLO-CHASSIS                    PIC X(021).
           05  BLO-DT-INCLUSAO                PIC 9(009).
           05  BLO-FILLER                     PIC X(020).
           05  BLO-FILLER1                    PIC X(020).
           05  BLO-FILLER2                    PIC X(020).
           05  BLO-HR-INCLUSAO                PIC 9(009).
           05  BLO-MUNIC-LEILAO               PIC X(005).
           05  BLO-MUNICIPIO                  PIC 9(009).
           05  BLO-NUM-OFIC                   PIC 9(009).
           05  BLO-NUM-PROCESSO               PIC 9(009).
           05  BLO-NUM-PROTOC                 PIC 9(009).
           05  BLO-PLACA-MERC                 PIC X(010).
           05  BLO-PLACA                      PIC X(010).
           05  BLO-TIP-BLOQ                   PIC X(006).
           05  BLO-USUARIO                    PIC X(008).
