      * WSD copybook for CODSEGCRLVDS (auto-generated)
       01  CODSEGCRLVDS.
           05  CODSEGCRLVDS-ROWID             PIC X(018).
           05  CSL-ANO-FICHA-X                PIC X(004).
           05  CSL-CATEGORIA-X                PIC X(006).
           05  CSL-CHASSI-X                   PIC X(021).
           05  CSL-COD-MOTIVO-X               PIC X(006).
           05  CSL-COD-SEG-X                  PIC X(006).
           05  CSL-CPF-CGC-X                  PIC X(014).
           05  CSL-DATA-AUT-X                 PIC X(010).
           05  CSL-DATA-EMIS-X                PIC X(010).
           05  CSL-DATA-REENVIO-X             PIC X(010).
           05  CSL-EMIS-LIC-X                 PIC X(030).
           05  CSL-ESPELHO-X                  PIC X(030).
           05  CSL-HORA-AUT-X                 PIC X(006).
           05  CSL-HORA-EMIS-X                PIC X(006).
           05  CSL-MUNICIPIO-X                PIC X(005).
           05  CSL-NRO-FICHA-X                PIC X(030).
           05  CSL-PLACA-X                    PIC X(010).
           05  CSL-RETORNO-X                  PIC X(030).
           05  CSL-TRANSACAO-X                PIC X(030).
           05  CSL-VIA-CRLV-X                 PIC X(030).
           05  CSL-ANO-FICHA                  PIC 9(009).
           05  CSL-CATEGORIA                  PIC X(006).
           05  CSL-CHASSI                     PIC X(021).
           05  CSL-COD-MOTIVO                 PIC 9(009).
           05  CSL-COD-SEG                    PIC 9(009).
           05  CSL-CPF-CGC                    PIC X(014).
           05  CSL-DATA-AUT                   PIC X(010).
           05  CSL-DATA-EMIS                  PIC X(010).
           05  CSL-DATA-REENVIO               PIC X(010).
           05  CSL-EMIS-LIC                   PIC X(030).
           05  CSL-ESPELHO                    PIC X(030).
           05  CSL-HORA-AUT                   PIC X(006).
           05  CSL-HORA-EMIS                  PIC X(006).
           05  CSL-MUNICIPIO                  PIC 9(009).
           05  CSL-NRO-FICHA                  PIC X(030).
           05  CSL-PLACA                      PIC X(010).
           05  CSL-RETORNO                    PIC X(030).
           05  CSL-TRANSACAO                  PIC X(030).
           05  CSL-VIA-CRLV                   PIC X(030).
