      * WSD copybook for DETTABDS (auto-generated)
       01  DETTABDS.
           05  DETTABDS-ROWID                 PIC X(018).
           05  TAB-CAR-NOME-X                 PIC X(040).
           05  TAB-CHAVE-X                    PIC X(030).
           05  TAB-CIR-MUNICIPIO-X            PIC X(005).
           05  TAB-CIR-MUNPRDESP-X            PIC X(030).
           05  TAB-CIR-MUNSERPRO-X            PIC X(030).
           05  TAB-DATA-X                     PIC X(010).
           05  TAB-DB-DATA-X                  PIC X(010).
           05  TAB-DB-MESEXT-X                PIC X(030).
           05  TAB-DB-MESLISTOES-X            PIC X(030).
           05  TAB-DEN-ENQPRD-X               PIC X(030).
           05  TAB-DEN-ESP-X                  PIC X(030).
           05  TAB-DEN-NOMCARROC-X            PIC X(030).
           05  TAB-DEN-NOMETIPO-X             PIC X(040).
           05  TAB-DEN-NOMMARCA-X             PIC X(006).
           05  TAB-DEN-TIPO-X                 PIC X(006).
           05  TAB-DESCR-MUN-X                PIC X(040).
           05  TAB-DST-CIRETRAN-X             PIC X(030).
           05  TAB-DST-DATADIST-X             PIC X(010).
           05  TAB-DST-ESPECIE-X              PIC X(006).
           05  TAB-DST-MUNICIPIO-X            PIC X(005).
           05  TAB-DST-PLACAFIN-X             PIC X(010).
           05  TAB-DST-REFERENCE-X            PIC X(030).
           05  TAB-ENQ-APREENSAO-X            PIC X(030).
           05  TAB-ENQ-ARTIGO-X               PIC X(030).
           05  TAB-ENQ-COMPETENC-X            PIC X(030).
           05  TAB-ENQ-DC-X                   PIC X(030).
           05  TAB-ENQ-DENATRAN-X             PIC X(030).
           05  TAB-ENQ-DESCRICAO-X            PIC X(040).
           05  TAB-ENQ-GRUPO-X                PIC X(030).
           05  TAB-ENQ-LETRA-X                PIC X(030).
           05  TAB-ENQ-PARAGRAFO-X            PIC X(030).
           05  TAB-ENQ-PERCENT-X              PIC X(030).
           05  TAB-ENQ-TIPO-X                 PIC X(006).
           05  TAB-ESP-NOME-X                 PIC X(040).
           05  TAB-EST-NOME-X                 PIC X(040).
           05  TAB-FAIXA-IPVA-X               PIC X(030).
           05  TAB-FILLER-X                   PIC X(020).
           05  TAB-FIN-NOME-X                 PIC X(040).
           05  TAB-IN-CATEGORIA-X             PIC X(006).
           05  TAB-IN-COMBUS-X                PIC X(006).
           05  TAB-IN-COR-X                   PIC X(030).
           05  TAB-IN-ESPECIE-X               PIC X(006).
           05  TAB-IN-RESTRICAO-X             PIC X(030).
           05  TAB-INCHAVE-X                  PIC X(030).
           05  TAB-INRET-EXEC-X               PIC X(030).
           05  TAB-INRET-TRANS-X              PIC X(030).
           05  TAB-INT-CIRETRAN-X             PIC X(030).
           05  TAB-INT-DATADIST-X             PIC X(010).
           05  TAB-INT-ESPECIE-X              PIC X(006).
           05  TAB-INT-MUNICIPIO-X            PIC X(005).
           05  TAB-INT-PLACAFIN-X             PIC X(010).
           05  TAB-INT-REFERENCE-X            PIC X(030).
           05  TAB-INTIPO-X                   PIC X(006).
           05  TAB-MAR-COD-X                  PIC X(030).
           05  TAB-MAR-TITULO-X               PIC X(030).
           05  TAB-MARCA-DESCR-X              PIC X(040).
           05  TAB-MRC-NOME-X                 PIC X(040).
           05  TAB-MTC-CIRETRAN-X             PIC X(030).
           05  TAB-MTC-DATADIST-X             PIC X(010).
           05  TAB-MTC-ESPECIE-X              PIC X(006).
           05  TAB-MTC-MUNICIPIO-X            PIC X(005).
           05  TAB-MTC-PLACAFIN-X             PIC X(010).
           05  TAB-MTC-REFERENCE-X            PIC X(030).
           05  TAB-MTI-CIRETRAN-X             PIC X(030).
           05  TAB-MTI-DATADIST-X             PIC X(010).
           05  TAB-MTI-ESPECIE-X              PIC X(006).
           05  TAB-MTI-MUNICIPIO-X            PIC X(005).
           05  TAB-MTI-PLACAFIN-X             PIC X(010).
           05  TAB-MTI-REFERENCE-X            PIC X(030).
           05  TAB-MUNIC-X                    PIC X(005).
           05  TAB-OTN-DTFIM-X                PIC X(030).
           05  TAB-OTN-VALOR-X                PIC X(030).
           05  TAB-PGU-ESTADO-X               PIC X(030).
           05  TAB-PGU-FIM-X                  PIC X(030).
           05  TAB-POLO-X                     PIC X(030).
           05  TAB-PRD-CEP-X                  PIC X(008).
           05  TAB-PRD-CIRETRAN-X             PIC X(030).
           05  TAB-PRD-DC-X                   PIC X(030).
           05  TAB-PRD-MUNICIPIO-X            PIC X(005).
           05  TAB-PRD-MUNSERPRO-X            PIC X(030).
           05  TAB-SEG-NOMECIA-X              PIC X(040).
           05  TAB-SER-CEP-X                  PIC X(008).
           05  TAB-SER-CIRETRAN-X             PIC X(030).
           05  TAB-SER-MUNICIPIO-X            PIC X(005).
           05  TAB-SER-MUNPRDESP-X            PIC X(030).
           05  TAB-STR-NOME-X                 PIC X(040).
           05  TAB-TIPO-X                     PIC X(006).
           05  TAB-VAL-DTFIM-X                PIC X(030).
           05  TAB-VAL-SMF-X                  PIC X(030).
           05  TAB-CAR-NOME                   PIC X(040).
           05  TAB-CHAVE                      PIC X(030).
           05  TAB-CIR-MUNICIPIO              PIC 9(009).
           05  TAB-CIR-MUNPRDESP              PIC X(030).
           05  TAB-CIR-MUNSERPRO              PIC X(030).
           05  TAB-DATA                       PIC X(010).
           05  TAB-DB-DATA                    PIC X(010).
           05  TAB-DB-MESEXT                  PIC X(030).
           05  TAB-DB-MESLISTOES              PIC X(030).
           05  TAB-DEN-ENQPRD                 PIC X(030).
           05  TAB-DEN-ESP                    PIC X(030).
           05  TAB-DEN-NOMCARROC              PIC X(030).
           05  TAB-DEN-NOMETIPO               PIC X(040).
           05  TAB-DEN-NOMMARCA               PIC X(006).
           05  TAB-DEN-TIPO                   PIC X(006).
           05  TAB-DESCR-MUN                  PIC X(040).
           05  TAB-DST-CIRETRAN               PIC X(030).
           05  TAB-DST-DATADIST               PIC X(010).
           05  TAB-DST-ESPECIE                PIC X(006).
           05  TAB-DST-MUNICIPIO              PIC 9(009).
           05  TAB-DST-PLACAFIN               PIC X(010).
           05  TAB-DST-REFERENCE              PIC X(030).
           05  TAB-ENQ-APREENSAO              PIC X(030).
           05  TAB-ENQ-ARTIGO                 PIC X(030).
           05  TAB-ENQ-COMPETENC              PIC X(030).
           05  TAB-ENQ-DC                     PIC X(030).
           05  TAB-ENQ-DENATRAN               PIC X(030).
           05  TAB-ENQ-DESCRICAO              PIC X(040).
           05  TAB-ENQ-GRUPO                  PIC X(030).
           05  TAB-ENQ-LETRA                  PIC X(030).
           05  TAB-ENQ-PARAGRAFO              PIC X(030).
           05  TAB-ENQ-PERCENT                PIC X(030).
           05  TAB-ENQ-TIPO                   PIC X(006).
           05  TAB-ESP-NOME                   PIC X(040).
           05  TAB-EST-NOME                   PIC X(040).
           05  TAB-FAIXA-IPVA                 PIC X(030).
           05  TAB-FILLER                     PIC X(020).
           05  TAB-FIN-NOME                   PIC X(040).
           05  TAB-IN-CATEGORIA               PIC X(006).
           05  TAB-IN-COMBUS                  PIC X(006).
           05  TAB-IN-COR                     PIC X(030).
           05  TAB-IN-ESPECIE                 PIC X(006).
           05  TAB-IN-RESTRICAO               PIC X(030).
           05  TAB-INCHAVE                    PIC X(030).
           05  TAB-INRET-EXEC                 PIC X(030).
           05  TAB-INRET-TRANS                PIC X(030).
           05  TAB-INT-CIRETRAN               PIC X(030).
           05  TAB-INT-DATADIST               PIC X(010).
           05  TAB-INT-ESPECIE                PIC X(006).
           05  TAB-INT-MUNICIPIO              PIC 9(009).
           05  TAB-INT-PLACAFIN               PIC X(010).
           05  TAB-INT-REFERENCE              PIC X(030).
           05  TAB-INTIPO                     PIC X(006).
           05  TAB-MAR-COD                    PIC X(030).
           05  TAB-MAR-TITULO                 PIC X(030).
           05  TAB-MARCA-DESCR                PIC X(040).
           05  TAB-MRC-NOME                   PIC X(040).
           05  TAB-MTC-CIRETRAN               PIC X(030).
           05  TAB-MTC-DATADIST               PIC X(010).
           05  TAB-MTC-ESPECIE                PIC X(006).
           05  TAB-MTC-MUNICIPIO              PIC 9(009).
           05  TAB-MTC-PLACAFIN               PIC X(010).
           05  TAB-MTC-REFERENCE              PIC X(030).
           05  TAB-MTI-CIRETRAN               PIC X(030).
           05  TAB-MTI-DATADIST               PIC X(010).
           05  TAB-MTI-ESPECIE                PIC X(006).
           05  TAB-MTI-MUNICIPIO              PIC 9(009).
           05  TAB-MTI-PLACAFIN               PIC X(010).
           05  TAB-MTI-REFERENCE              PIC X(030).
           05  TAB-MUNIC                      PIC X(005).
           05  TAB-OTN-DTFIM                  PIC X(030).
           05  TAB-OTN-VALOR                  PIC X(030).
           05  TAB-PGU-ESTADO                 PIC X(030).
           05  TAB-PGU-FIM                    PIC X(030).
           05  TAB-POLO                       PIC X(030).
           05  TAB-PRD-CEP                    PIC X(008).
           05  TAB-PRD-CIRETRAN               PIC X(030).
           05  TAB-PRD-DC                     PIC X(030).
           05  TAB-PRD-MUNICIPIO              PIC 9(009).
           05  TAB-PRD-MUNSERPRO              PIC X(030).
           05  TAB-SEG-NOMECIA                PIC X(040).
           05  TAB-SER-CEP                    PIC X(008).
           05  TAB-SER-CIRETRAN               PIC X(030).
           05  TAB-SER-MUNICIPIO              PIC 9(009).
           05  TAB-SER-MUNPRDESP              PIC X(030).
           05  TAB-STR-NOME                   PIC X(040).
           05  TAB-TIPO                       PIC X(006).
           05  TAB-VAL-DTFIM                  PIC X(030).
           05  TAB-VAL-SMF                    PIC X(030).
