      * WSD copybook for PRODPLIDS (auto-generated)
       01  PRODPLIDS.
           05  PRODPLIDS-ROWID                PIC X(018).
           05  PLI-ANOFABR-X                  PIC X(004).
           05  PLI-ANOMOD-X                   PIC X(004).
           05  PLI-BAIRRO-ANT-X               PIC X(040).
           05  PLI-BAIRRO-X                   PIC X(040).
           05  PLI-BAIXA-X                    PIC X(030).
           05  PLI-BLOQUEIO-X                 PIC X(030).
           05  PLI-CAP-CAR-X                  PIC X(030).
           05  PLI-CAP-PAS-X                  PIC X(030).
           05  PLI-CARROCERIA-X               PIC X(030).
           05  PLI-CATEGORIA-X                PIC X(006).
           05  PLI-CEP-ANT-X                  PIC X(008).
           05  PLI-CEP-ANTER-X                PIC X(008).
           05  PLI-CEP-ATUAL-X                PIC X(008).
           05  PLI-CEP-X                      PIC X(008).
           05  PLI-CHASSIS-REG-X              PIC X(021).
           05  PLI-CHASSIS-X                  PIC X(021).
           05  PLI-CILINDRADA-X               PIC X(030).
           05  PLI-CMT-X                      PIC X(030).
           05  PLI-COMBUSTIVEL-X              PIC X(006).
           05  PLI-COMODATO-X                 PIC X(030).
           05  PLI-COMPL-ANT-X                PIC X(040).
           05  PLI-COMPL-X                    PIC X(040).
           05  PLI-CONF-X                     PIC X(030).
           05  PLI-COR-X                      PIC X(030).
           05  PLI-CPF-CGC-ANT-X              PIC X(014).
           05  PLI-CPF-CGCG-X                 PIC X(014).
           05  PLI-DESP-SSP-X                 PIC X(030).
           05  PLI-DIGI-X                     PIC X(030).
           05  PLI-DT-DESBLOQ-X               PIC X(010).
           05  PLI-DT-EMIS-X                  PIC X(010).
           05  PLI-DT-EMISLIC-X               PIC X(010).
           05  PLI-DT-INCLUSAO-X              PIC X(010).
           05  PLI-DT-MOVIMENTO-X             PIC X(010).
           05  PLI-EMIS-LIC-X                 PIC X(030).
           05  PLI-ENDERECO-ANT-X             PIC X(040).
           05  PLI-ENDERECO-X                 PIC X(040).
           05  PLI-ESPECIE-X                  PIC X(006).
           05  PLI-FILLER1-X                  PIC X(020).
           05  PLI-FILLER11-X                 PIC X(020).
           05  PLI-FILLER12-X                 PIC X(020).
           05  PLI-FILLER13-X                 PIC X(020).
           05  PLI-FILLER14-X                 PIC X(020).
           05  PLI-FILLER2-X                  PIC X(020).
           05  PLI-FILLER3-X                  PIC X(020).
           05  PLI-FILLER4-X                  PIC X(020).
           05  PLI-FILLER5-X                  PIC X(020).
           05  PLI-FILLER6-X                  PIC X(020).
           05  PLI-FILLER7-X                  PIC X(020).
           05  PLI-FILLER8-X                  PIC X(020).
           05  PLI-FILLER9-X                  PIC X(020).
           05  PLI-FINANC-ANT-X               PIC X(030).
           05  PLI-FINANC-X                   PIC X(030).
           05  PLI-FX-IPVA-X                  PIC X(030).
           05  PLI-GUINCHO-X                  PIC X(030).
           05  PLI-HORA-X                     PIC X(006).
           05  PLI-ID-CONTR-ANT-X             PIC X(030).
           05  PLI-ID-CONTR-X                 PIC X(030).
           05  PLI-IDENT-CARGA-X              PIC X(030).
           05  PLI-INDIC-RTB-X                PIC X(030).
           05  PLI-IPVA-X                     PIC X(030).
           05  PLI-LETRANT-X                  PIC X(030).
           05  PLI-MARCA-X                    PIC X(006).
           05  PLI-MULTA-DSV-X                PIC X(030).
           05  PLI-MULTA-X                    PIC X(030).
           05  PLI-MUN-ANT-X                  PIC X(005).
           05  PLI-MUN-X                      PIC X(030).
           05  PLI-MUNICIPIO-ANT-X            PIC X(005).
           05  PLI-MUNICIPIO-X                PIC X(005).
           05  PLI-NOMEPROPR-ANT-X            PIC X(040).
           05  PLI-NOMEPROPR-X                PIC X(040).
           05  PLI-NRO-EIXOS-X                PIC X(030).
           05  PLI-NUM-RENAVAM-X              PIC X(011).
           05  PLI-NUMERANT1-X                PIC X(030).
           05  PLI-NUMERANT2-X                PIC X(030).
           05  PLI-NUMERO-ANT-X               PIC X(030).
           05  PLI-NUMERO-AT-X                PIC X(030).
           05  PLI-OPCAO-X                    PIC X(030).
           05  PLI-ORG-RG-ANT-X               PIC X(030).
           05  PLI-ORG-RG-X                   PIC X(030).
           05  PLI-PBT-X                      PIC X(030).
           05  PLI-PLA-ANT-MERC-X             PIC X(030).
           05  PLI-PLACA-MERC-X               PIC X(010).
           05  PLI-PLACA-X                    PIC X(010).
           05  PLI-POTENCIA-X                 PIC X(030).
           05  PLI-PROCEDENCIA-X              PIC X(030).
           05  PLI-RESTR-ADMIN-X              PIC X(030).
           05  PLI-RESTR-FIN-ANT-X            PIC X(030).
           05  PLI-RESTR-FIN-X                PIC X(030).
           05  PLI-RESTR-JUDIC-X              PIC X(030).
           05  PLI-RESTR-TRIB-X               PIC X(030).
           05  PLI-RG-ANT-X                   PIC X(030).
           05  PLI-RG-X                       PIC X(030).
           05  PLI-SISTSEG-BASC-X             PIC X(030).
           05  PLI-TEL-X                      PIC X(030).
           05  PLI-TIPO-X                     PIC X(006).
           05  PLI-TQUEMULTI-X                PIC X(030).
           05  PLI-UF-PLACA-ANT-X             PIC X(010).
           05  PLI-UF-RG-ANT-X                PIC X(002).
           05  PLI-UF-RG-X                    PIC X(002).
           05  PLI-USUALTER-X                 PIC X(030).
           05  PLI-USUCAR-X                   PIC X(030).
           05  PLI-VIA-CERT-X                 PIC X(030).
           05  PLI-VIST-X                     PIC X(030).
           05  PLI-ANOFABR                    PIC 9(009).
           05  PLI-ANOMOD                     PIC 9(009).
           05  PLI-BAIRRO-ANT                 PIC X(040).
           05  PLI-BAIRRO                     PIC X(040).
           05  PLI-BAIXA                      PIC X(030).
           05  PLI-BLOQUEIO                   PIC X(030).
           05  PLI-CAP-CAR                    PIC X(030).
           05  PLI-CAP-PAS                    PIC X(030).
           05  PLI-CARROCERIA                 PIC X(030).
           05  PLI-CATEGORIA                  PIC X(006).
           05  PLI-CEP-ANT                    PIC X(008).
           05  PLI-CEP-ANTER                  PIC X(008).
           05  PLI-CEP-ATUAL                  PIC X(008).
           05  PLI-CEP                        PIC X(008).
           05  PLI-CHASSIS-REG                PIC X(021).
           05  PLI-CHASSIS                    PIC X(021).
           05  PLI-CILINDRADA                 PIC X(030).
           05  PLI-CMT                        PIC X(030).
           05  PLI-COMBUSTIVEL                PIC X(006).
           05  PLI-COMODATO                   PIC X(030).
           05  PLI-COMPL-ANT                  PIC X(040).
           05  PLI-COMPL                      PIC X(040).
           05  PLI-CONF                       PIC X(030).
           05  PLI-COR                        PIC X(030).
           05  PLI-CPF-CGC-ANT                PIC X(014).
           05  PLI-CPF-CGCG                   PIC X(014).
           05  PLI-DESP-SSP                   PIC X(030).
           05  PLI-DIGI                       PIC X(030).
           05  PLI-DT-DESBLOQ                 PIC 9(009).
           05  PLI-DT-EMIS                    PIC 9(009).
           05  PLI-DT-EMISLIC                 PIC 9(009).
           05  PLI-DT-INCLUSAO                PIC 9(009).
           05  PLI-DT-MOVIMENTO               PIC 9(009).
           05  PLI-EMIS-LIC                   PIC X(030).
           05  PLI-ENDERECO-ANT               PIC X(040).
           05  PLI-ENDERECO                   PIC X(040).
           05  PLI-ESPECIE                    PIC X(006).
           05  PLI-FILLER1                    PIC X(020).
           05  PLI-FILLER11                   PIC X(020).
           05  PLI-FILLER12                   PIC X(020).
           05  PLI-FILLER13                   PIC X(020).
           05  PLI-FILLER14                   PIC X(020).
           05  PLI-FILLER2                    PIC X(020).
           05  PLI-FILLER3                    PIC X(020).
           05  PLI-FILLER4                    PIC X(020).
           05  PLI-FILLER5                    PIC X(020).
           05  PLI-FILLER6                    PIC X(020).
           05  PLI-FILLER7                    PIC X(020).
           05  PLI-FILLER8                    PIC X(020).
           05  PLI-FILLER9                    PIC X(020).
           05  PLI-FINANC-ANT                 PIC X(030).
           05  PLI-FINANC                     PIC X(030).
           05  PLI-FX-IPVA                    PIC X(030).
           05  PLI-GUINCHO                    PIC X(030).
           05  PLI-HORA                       PIC X(006).
           05  PLI-ID-CONTR-ANT               PIC X(030).
           05  PLI-ID-CONTR                   PIC X(030).
           05  PLI-IDENT-CARGA                PIC X(030).
           05  PLI-INDIC-RTB                  PIC X(030).
           05  PLI-IPVA                       PIC X(030).
           05  PLI-LETRANT                    PIC X(030).
           05  PLI-MARCA                      PIC X(006).
           05  PLI-MULTA-DSV                  PIC X(030).
           05  PLI-MULTA                      PIC X(030).
           05  PLI-MUN-ANT                    PIC X(005).
           05  PLI-MUN                        PIC X(030).
           05  PLI-MUNICIPIO-ANT              PIC 9(009).
           05  PLI-MUNICIPIO                  PIC 9(009).
           05  PLI-NOMEPROPR-ANT              PIC X(040).
           05  PLI-NOMEPROPR                  PIC X(040).
           05  PLI-NRO-EIXOS                  PIC X(030).
           05  PLI-NUM-RENAVAM                PIC 9(009).
           05  PLI-NUMERANT1                  PIC X(030).
           05  PLI-NUMERANT2                  PIC X(030).
           05  PLI-NUMERO-ANT                 PIC X(030).
           05  PLI-NUMERO-AT                  PIC X(030).
           05  PLI-OPCAO                      PIC X(030).
           05  PLI-ORG-RG-ANT                 PIC X(030).
           05  PLI-ORG-RG                     PIC X(030).
           05  PLI-PBT                        PIC X(030).
           05  PLI-PLA-ANT-MERC               PIC X(030).
           05  PLI-PLACA-MERC                 PIC X(010).
           05  PLI-PLACA                      PIC X(010).
           05  PLI-POTENCIA                   PIC X(030).
           05  PLI-PROCEDENCIA                PIC X(030).
           05  PLI-RESTR-ADMIN                PIC X(030).
           05  PLI-RESTR-FIN-ANT              PIC X(030).
           05  PLI-RESTR-FIN                  PIC X(030).
           05  PLI-RESTR-JUDIC                PIC X(030).
           05  PLI-RESTR-TRIB                 PIC X(030).
           05  PLI-RG-ANT                     PIC X(030).
           05  PLI-RG                         PIC X(030).
           05  PLI-SISTSEG-BASC               PIC X(030).
           05  PLI-TEL                        PIC X(030).
           05  PLI-TIPO                       PIC X(006).
           05  PLI-TQUEMULTI                  PIC X(030).
           05  PLI-UF-PLACA-ANT               PIC X(010).
           05  PLI-UF-RG-ANT                  PIC X(002).
           05  PLI-UF-RG                      PIC X(002).
           05  PLI-USUALTER                   PIC X(030).
           05  PLI-USUCAR                     PIC X(030).
           05  PLI-VIA-CERT                   PIC X(030).
           05  PLI-VIST                       PIC X(030).
