      * WSD copybook for ESTAMPAGEMDS (auto-generated)
       01  ESTAMPAGEMDS.
           05  ESTAMPAGEMDS-ROWID             PIC X(018).
           05  ETP-AUTORIZACAO-X              PIC X(030).
           05  ETP-CNPJ-ESTAMP-X              PIC X(014).
           05  ETP-COD-RET-EV02-X             PIC X(006).
           05  ETP-COMPATIBIL-X               PIC X(030).
           05  ETP-DT-INCLUSAO-X              PIC X(010).
           05  ETP-DT-SERVICO-X               PIC X(010).
           05  ETP-DT-T252-X                  PIC X(010).
           05  ETP-HR-INCLUSAO-X              PIC X(006).
           05  ETP-HR-T252-X                  PIC X(006).
           05  ETP-INDIC-BIN-X                PIC X(030).
           05  ETP-MOT-AUTORIZ-X              PIC X(030).
           05  ETP-MUNIC-EV02-X               PIC X(005).
           05  ETP-PLACA-SERIAL-X             PIC X(010).
           05  ETP-PLACA-TIPO-X               PIC X(010).
           05  ETP-PLACA-UF-X                 PIC X(010).
           05  ETP-PLACA-X                    PIC X(010).
           05  ETP-RENAVAM-X                  PIC X(011).
           05  ETP-STATUS-X                   PIC X(020).
           05  ETP-TIP-OFIC-X                 PIC X(006).
           05  ETP-UF-EV02-X                  PIC X(002).
           05  ETP-USUARIO-250-X              PIC X(008).
           05  ETP-AUTORIZACAO                PIC X(030).
           05  ETP-CNPJ-ESTAMP                PIC X(014).
           05  ETP-COD-RET-EV02               PIC 9(009).
           05  ETP-COMPATIBIL                 PIC X(030).
           05  ETP-DT-INCLUSAO                PIC 9(009).
           05  ETP-DT-SERVICO                 PIC 9(009).
           05  ETP-DT-T252                    PIC 9(009).
           05  ETP-HR-INCLUSAO                PIC 9(009).
           05  ETP-HR-T252                    PIC 9(009).
           05  ETP-INDIC-BIN                  PIC X(030).
           05  ETP-MOT-AUTORIZ                PIC X(030).
           05  ETP-MUNIC-EV02                 PIC X(005).
           05  ETP-PLACA-SERIAL               PIC X(010).
           05  ETP-PLACA-TIPO                 PIC X(010).
           05  ETP-PLACA-UF                   PIC X(010).
           05  ETP-PLACA                      PIC X(010).
           05  ETP-RENAVAM                    PIC X(011).
           05  ETP-STATUS                     PIC X(020).
           05  ETP-TIP-OFIC                   PIC X(006).
           05  ETP-UF-EV02                    PIC X(002).
           05  ETP-USUARIO-250                PIC X(008).
