      * WSD copybook for AUTENTICACAODS (auto-generated)
       01  AUTENTICACAODS.
           05  AUTENTICACAODS-ROWID           PIC X(018).
           05  AUT-BANCO-X                    PIC X(030).
           05  AUT-COD-PAG-X                  PIC X(006).
           05  AUT-CPF-CGC-X                  PIC X(014).
           05  AUT-CPF-X                      PIC X(011).
           05  AUT-DATA-ATUAL-X               PIC X(010).
           05  AUT-DATA-INCL-X                PIC X(010).
           05  AUT-DATA-PAGTO-X               PIC X(010).
           05  AUT-DESP-SSP-X                 PIC X(030).
           05  AUT-DT-INCLUSAO-X              PIC X(010).
           05  AUT-FILLER-X                   PIC X(020).
           05  AUT-HORA-INCL-X                PIC X(006).
           05  AUT-HR-INCLUSAO-X              PIC X(006).
           05  AUT-MUNICIPIO-X                PIC X(005).
           05  AUT-OBSERV-X                   PIC X(040).
           05  AUT-ORIGEM-X                   PIC X(030).
           05  AUT-PGUREG-X                   PIC X(030).
           05  AUT-PLACA-MERC-X               PIC X(010).
           05  AUT-PLACA-X                    PIC X(010).
           05  AUT-QTDE-UTIL-X                PIC X(030).
           05  AUT-RENAVAM-X                  PIC X(011).
           05  AUT-SENHA-X                    PIC X(030).
           05  AUT-SITUACAO-X                 PIC X(020).
           05  AUT-TIPO-X                     PIC X(006).
           05  AUT-VALOR-X                    PIC X(030).
           05  AUT-BANCO                      PIC X(030).
           05  AUT-COD-PAG                    PIC 9(009).
           05  AUT-CPF-CGC                    PIC X(014).
           05  AUT-CPF                        PIC X(011).
           05  AUT-DATA-ATUAL                 PIC X(010).
           05  AUT-DATA-INCL                  PIC X(010).
           05  AUT-DATA-PAGTO                 PIC X(010).
           05  AUT-DESP-SSP                   PIC X(030).
           05  AUT-DT-INCLUSAO                PIC 9(009).
           05  AUT-FILLER                     PIC X(020).
           05  AUT-HORA-INCL                  PIC X(006).
           05  AUT-HR-INCLUSAO                PIC 9(009).
           05  AUT-MUNICIPIO                  PIC 9(009).
           05  AUT-OBSERV                     PIC X(040).
           05  AUT-ORIGEM                     PIC X(030).
           05  AUT-PGUREG                     PIC X(030).
           05  AUT-PLACA-MERC                 PIC X(010).
           05  AUT-PLACA                      PIC X(010).
           05  AUT-QTDE-UTIL                  PIC X(030).
           05  AUT-RENAVAM                    PIC X(011).
           05  AUT-SENHA                      PIC X(030).
           05  AUT-SITUACAO                   PIC X(020).
           05  AUT-TIPO                       PIC X(006).
           05  AUT-VALOR                      PIC X(030).
