      * WSD copybook for TAXADS (auto-generated)
       01  TAXADS.
           05  TAXADS-ROWID                   PIC X(018).
           05  TAX-BANCO-X                    PIC X(030).
           05  TAX-COD-BANCO-X                PIC X(006).
           05  TAX-COD-PAG-X                  PIC X(006).
           05  TAX-COD-SERVICO-X              PIC X(006).
           05  TAX-CPF-CGC-X                  PIC X(014).
           05  TAX-CPF-X                      PIC X(011).
           05  TAX-DATAINCL-X                 PIC X(010).
           05  TAX-DESP-SSP-X                 PIC X(030).
           05  TAX-DT-ATUAL-X                 PIC X(010).
           05  TAX-DT-CONTABIL-X              PIC X(010).
           05  TAX-DT-CONTB-X                 PIC X(010).
           05  TAX-DT-INCLUSAO-X              PIC X(010).
           05  TAX-DT-PAGTO-X                 PIC X(010).
           05  TAX-DT-UTILIZA-X               PIC X(010).
           05  TAX-DT-VALID-X                 PIC X(010).
           05  TAX-FILLER1-X                  PIC X(020).
           05  TAX-FILLER2-X                  PIC X(020).
           05  TAX-HORAINCL-X                 PIC X(006).
           05  TAX-HR-INCLUSAO-X              PIC X(006).
           05  TAX-HR-VALID-X                 PIC X(006).
           05  TAX-ID-FIM-X                   PIC X(030).
           05  TAX-ID-PIX-X                   PIC X(030).
           05  TAX-MUNICIPIO-X                PIC X(005).
           05  TAX-NSU-PROD-X                 PIC X(030).
           05  TAX-NSUBANCO-X                 PIC X(030).
           05  TAX-NSUPRODESP-X               PIC X(030).
           05  TAX-PGU-X                      PIC X(030).
           05  TAX-PLACA-MERC-X               PIC X(010).
           05  TAX-REGISTRO-X                 PIC X(030).
           05  TAX-RENACH-X                   PIC X(030).
           05  TAX-RENAVAM-X                  PIC X(011).
           05  TAX-SENHA-SEFAZ-X              PIC X(030).
           05  TAX-SENHA-X                    PIC X(030).
           05  TAX-SITUACAO-X                 PIC X(020).
           05  TAX-TIPO-X                     PIC X(006).
           05  TAX-TRANSACAO-X                PIC X(030).
           05  TAX-USUARIO-X                  PIC X(008).
           05  TAX-VALOR-X                    PIC X(030).
           05  TAX-BANCO                      PIC X(030).
           05  TAX-COD-BANCO                  PIC 9(009).
           05  TAX-COD-PAG                    PIC 9(009).
           05  TAX-COD-SERVICO                PIC 9(009).
           05  TAX-CPF-CGC                    PIC X(014).
           05  TAX-CPF                        PIC X(011).
           05  TAX-DATAINCL                   PIC X(010).
           05  TAX-DESP-SSP                   PIC X(030).
           05  TAX-DT-ATUAL                   PIC 9(009).
           05  TAX-DT-CONTABIL                PIC 9(009).
           05  TAX-DT-CONTB                   PIC 9(009).
           05  TAX-DT-INCLUSAO                PIC 9(009).
           05  TAX-DT-PAGTO                   PIC 9(009).
           05  TAX-DT-UTILIZA                 PIC 9(009).
           05  TAX-DT-VALID                   PIC 9(009).
           05  TAX-FILLER1                    PIC X(020).
           05  TAX-FILLER2                    PIC X(020).
           05  TAX-HORAINCL                   PIC X(006).
           05  TAX-HR-INCLUSAO                PIC 9(009).
           05  TAX-HR-VALID                   PIC 9(009).
           05  TAX-ID-FIM                     PIC X(030).
           05  TAX-ID-PIX                     PIC X(030).
           05  TAX-MUNICIPIO                  PIC 9(009).
           05  TAX-NSU-PROD                   PIC X(030).
           05  TAX-NSUBANCO                   PIC X(030).
           05  TAX-NSUPRODESP                 PIC X(030).
           05  TAX-PGU                        PIC X(030).
           05  TAX-PLACA-MERC                 PIC X(010).
           05  TAX-REGISTRO                   PIC X(030).
           05  TAX-RENACH                     PIC X(030).
           05  TAX-RENAVAM                    PIC X(011).
           05  TAX-SENHA-SEFAZ                PIC X(030).
           05  TAX-SENHA                      PIC X(030).
           05  TAX-SITUACAO                   PIC X(020).
           05  TAX-TIPO                       PIC X(006).
           05  TAX-TRANSACAO                  PIC X(030).
           05  TAX-USUARIO                    PIC X(008).
           05  TAX-VALOR                      PIC X(030).
