      * WSD copybook for PRODPLCDS (auto-generated)
       01  PRODPLCDS.
           05  PRODPLCDS-ROWID                PIC X(018).
           05  PLC-ANOFABR-X                  PIC X(004).
           05  PLC-ANOMOD-X                   PIC X(004).
           05  PLC-BAIRRO-ANT-X               PIC X(040).
           05  PLC-BAIRRO-X                   PIC X(040).
           05  PLC-BAIXA-X                    PIC X(030).
           05  PLC-BLOQUEIO-X                 PIC X(030).
           05  PLC-CAP-CAR-X                  PIC X(030).
           05  PLC-CAP-PAS-X                  PIC X(030).
           05  PLC-CARROCERIA-X               PIC X(030).
           05  PLC-CATEGORIA-X                PIC X(006).
           05  PLC-CEP-ANT-X                  PIC X(008).
           05  PLC-CEP-ANTER-X                PIC X(008).
           05  PLC-CEP-ATUAL-X                PIC X(008).
           05  PLC-CEP-X                      PIC X(008).
           05  PLC-CHASSIS-REG-X              PIC X(021).
           05  PLC-CHASSIS-X                  PIC X(021).
           05  PLC-CILINDRADA-X               PIC X(030).
           05  PLC-CMT-X                      PIC X(030).
           05  PLC-COMBUSTIVEL-X              PIC X(006).
           05  PLC-COMODATO-X                 PIC X(030).
           05  PLC-COMPL-ANT-X                PIC X(040).
           05  PLC-COMPL-X                    PIC X(040).
           05  PLC-CONF-X                     PIC X(030).
           05  PLC-COR-X                      PIC X(030).
           05  PLC-CPF-CGC-ANT-X              PIC X(014).
           05  PLC-CPF-CGCG-X                 PIC X(014).
           05  PLC-DESP-SSP-X                 PIC X(030).
           05  PLC-DIGI-X                     PIC X(030).
           05  PLC-DT-DESBLOQ-X               PIC X(010).
           05  PLC-DT-EMIS-X                  PIC X(010).
           05  PLC-DT-EMISLIC-X               PIC X(010).
           05  PLC-DT-INCLUSAO-X              PIC X(010).
           05  PLC-DT-MOVIMENTO-X             PIC X(010).
           05  PLC-EMIS-LIC-X                 PIC X(030).
           05  PLC-ENDERECO-ANT-X             PIC X(040).
           05  PLC-ENDERECO-X                 PIC X(040).
           05  PLC-ESPECIE-X                  PIC X(006).
           05  PLC-FILLER1-X                  PIC X(020).
           05  PLC-FILLER11-X                 PIC X(020).
           05  PLC-FILLER12-X                 PIC X(020).
           05  PLC-FILLER13-X                 PIC X(020).
           05  PLC-FILLER14-X                 PIC X(020).
           05  PLC-FILLER2-X                  PIC X(020).
           05  PLC-FILLER3-X                  PIC X(020).
           05  PLC-FILLER4-X                  PIC X(020).
           05  PLC-FILLER5-X                  PIC X(020).
           05  PLC-FILLER6-X                  PIC X(020).
           05  PLC-FILLER7-X                  PIC X(020).
           05  PLC-FILLER8-X                  PIC X(020).
           05  PLC-FILLER9-X                  PIC X(020).
           05  PLC-FINANC-ANT-X               PIC X(030).
           05  PLC-FINANC-X                   PIC X(030).
           05  PLC-FX-IPVA-X                  PIC X(030).
           05  PLC-GUINCHO-X                  PIC X(030).
           05  PLC-HORA-X                     PIC X(006).
           05  PLC-ID-CONTR-ANT-X             PIC X(030).
           05  PLC-ID-CONTR-X                 PIC X(030).
           05  PLC-IDENT-CARGA-X              PIC X(030).
           05  PLC-INDIC-RTB-X                PIC X(030).
           05  PLC-IPVA-X                     PIC X(030).
           05  PLC-LETRANT-X                  PIC X(030).
           05  PLC-MARCA-X                    PIC X(006).
           05  PLC-MULTA-DSV-X                PIC X(030).
           05  PLC-MULTA-X                    PIC X(030).
           05  PLC-MUN-ANT-X                  PIC X(005).
           05  PLC-MUN-X                      PIC X(030).
           05  PLC-MUNICIPIO-ANT-X            PIC X(005).
           05  PLC-MUNICIPIO-X                PIC X(005).
           05  PLC-NOMEPROPR-ANT-X            PIC X(040).
           05  PLC-NOMEPROPR-X                PIC X(040).
           05  PLC-NRO-EIXOS-X                PIC X(030).
           05  PLC-NUM-RENAVAM-X              PIC X(011).
           05  PLC-NUMERANT1-X                PIC X(030).
           05  PLC-NUMERANT2-X                PIC X(030).
           05  PLC-NUMERO-ANT-X               PIC X(030).
           05  PLC-NUMERO-AT-X                PIC X(030).
           05  PLC-OPCAO-X                    PIC X(030).
           05  PLC-ORG-RG-ANT-X               PIC X(030).
           05  PLC-ORG-RG-X                   PIC X(030).
           05  PLC-PBT-X                      PIC X(030).
           05  PLC-PLA-ANT-MERC-X             PIC X(030).
           05  PLC-PLACA-MERC-X               PIC X(010).
           05  PLC-PLACA-X                    PIC X(010).
           05  PLC-POTENCIA-X                 PIC X(030).
           05  PLC-PROCEDENCIA-X              PIC X(030).
           05  PLC-RESTR-ADMIN-X              PIC X(030).
           05  PLC-RESTR-FIN-ANT-X            PIC X(030).
           05  PLC-RESTR-FIN-X                PIC X(030).
           05  PLC-RESTR-JUDIC-X              PIC X(030).
           05  PLC-RESTR-TRIB-X               PIC X(030).
           05  PLC-RG-ANT-X                   PIC X(030).
           05  PLC-RG-X                       PIC X(030).
           05  PLC-SISTSEG-BASC-X             PIC X(030).
           05  PLC-TEL-X                      PIC X(030).
           05  PLC-TIPO-X                     PIC X(006).
           05  PLC-TQUEMULTI-X                PIC X(030).
           05  PLC-UF-PLACA-ANT-X             PIC X(010).
           05  PLC-UF-RG-ANT-X                PIC X(002).
           05  PLC-UF-RG-X                    PIC X(002).
           05  PLC-USUALTER-X                 PIC X(030).
           05  PLC-USUCAR-X                   PIC X(030).
           05  PLC-VIA-CERT-X                 PIC X(030).
           05  PLC-VIST-X                     PIC X(030).
           05  PLC-ANOFABR                    PIC 9(009).
           05  PLC-ANOMOD                     PIC 9(009).
           05  PLC-BAIRRO-ANT                 PIC X(040).
           05  PLC-BAIRRO                     PIC X(040).
           05  PLC-BAIXA                      PIC X(030).
           05  PLC-BLOQUEIO                   PIC X(030).
           05  PLC-CAP-CAR                    PIC X(030).
           05  PLC-CAP-PAS                    PIC X(030).
           05  PLC-CARROCERIA                 PIC X(030).
           05  PLC-CATEGORIA                  PIC X(006).
           05  PLC-CEP-ANT                    PIC X(008).
           05  PLC-CEP-ANTER                  PIC X(008).
           05  PLC-CEP-ATUAL                  PIC X(008).
           05  PLC-CEP                        PIC X(008).
           05  PLC-CHASSIS-REG                PIC X(021).
           05  PLC-CHASSIS                    PIC X(021).
           05  PLC-CILINDRADA                 PIC X(030).
           05  PLC-CMT                        PIC X(030).
           05  PLC-COMBUSTIVEL                PIC X(006).
           05  PLC-COMODATO                   PIC X(030).
           05  PLC-COMPL-ANT                  PIC X(040).
           05  PLC-COMPL                      PIC X(040).
           05  PLC-CONF                       PIC X(030).
           05  PLC-COR                        PIC X(030).
           05  PLC-CPF-CGC-ANT                PIC X(014).
           05  PLC-CPF-CGCG                   PIC X(014).
           05  PLC-DESP-SSP                   PIC X(030).
           05  PLC-DIGI                       PIC X(030).
           05  PLC-DT-DESBLOQ                 PIC 9(009).
           05  PLC-DT-EMIS                    PIC 9(009).
           05  PLC-DT-EMISLIC                 PIC 9(009).
           05  PLC-DT-INCLUSAO                PIC 9(009).
           05  PLC-DT-MOVIMENTO               PIC 9(009).
           05  PLC-EMIS-LIC                   PIC X(030).
           05  PLC-ENDERECO-ANT               PIC X(040).
           05  PLC-ENDERECO                   PIC X(040).
           05  PLC-ESPECIE                    PIC X(006).
           05  PLC-FILLER1                    PIC X(020).
           05  PLC-FILLER11                   PIC X(020).
           05  PLC-FILLER12                   PIC X(020).
           05  PLC-FILLER13                   PIC X(020).
           05  PLC-FILLER14                   PIC X(020).
           05  PLC-FILLER2                    PIC X(020).
           05  PLC-FILLER3                    PIC X(020).
           05  PLC-FILLER4                    PIC X(020).
           05  PLC-FILLER5                    PIC X(020).
           05  PLC-FILLER6                    PIC X(020).
           05  PLC-FILLER7                    PIC X(020).
           05  PLC-FILLER8                    PIC X(020).
           05  PLC-FILLER9                    PIC X(020).
           05  PLC-FINANC-ANT                 PIC X(030).
           05  PLC-FINANC                     PIC X(030).
           05  PLC-FX-IPVA                    PIC X(030).
           05  PLC-GUINCHO                    PIC X(030).
           05  PLC-HORA                       PIC X(006).
           05  PLC-ID-CONTR-ANT               PIC X(030).
           05  PLC-ID-CONTR                   PIC X(030).
           05  PLC-IDENT-CARGA                PIC X(030).
           05  PLC-INDIC-RTB                  PIC X(030).
           05  PLC-IPVA                       PIC X(030).
           05  PLC-LETRANT                    PIC X(030).
           05  PLC-MARCA                      PIC X(006).
           05  PLC-MULTA-DSV                  PIC X(030).
           05  PLC-MULTA                      PIC X(030).
           05  PLC-MUN-ANT                    PIC X(005).
           05  PLC-MUN                        PIC X(030).
           05  PLC-MUNICIPIO-ANT              PIC 9(009).
           05  PLC-MUNICIPIO                  PIC 9(009).
           05  PLC-NOMEPROPR-ANT              PIC X(040).
           05  PLC-NOMEPROPR                  PIC X(040).
           05  PLC-NRO-EIXOS                  PIC X(030).
           05  PLC-NUM-RENAVAM                PIC 9(009).
           05  PLC-NUMERANT1                  PIC X(030).
           05  PLC-NUMERANT2                  PIC X(030).
           05  PLC-NUMERO-ANT                 PIC X(030).
           05  PLC-NUMERO-AT                  PIC X(030).
           05  PLC-OPCAO                      PIC X(030).
           05  PLC-ORG-RG-ANT                 PIC X(030).
           05  PLC-ORG-RG                     PIC X(030).
           05  PLC-PBT                        PIC X(030).
           05  PLC-PLA-ANT-MERC               PIC X(030).
           05  PLC-PLACA-MERC                 PIC X(010).
           05  PLC-PLACA                      PIC X(010).
           05  PLC-POTENCIA                   PIC X(030).
           05  PLC-PROCEDENCIA                PIC X(030).
           05  PLC-RESTR-ADMIN                PIC X(030).
           05  PLC-RESTR-FIN-ANT              PIC X(030).
           05  PLC-RESTR-FIN                  PIC X(030).
           05  PLC-RESTR-JUDIC                PIC X(030).
           05  PLC-RESTR-TRIB                 PIC X(030).
           05  PLC-RG-ANT                     PIC X(030).
           05  PLC-RG                         PIC X(030).
           05  PLC-SISTSEG-BASC               PIC X(030).
           05  PLC-TEL                        PIC X(030).
           05  PLC-TIPO                       PIC X(006).
           05  PLC-TQUEMULTI                  PIC X(030).
           05  PLC-UF-PLACA-ANT               PIC X(010).
           05  PLC-UF-RG-ANT                  PIC X(002).
           05  PLC-UF-RG                      PIC X(002).
           05  PLC-USUALTER                   PIC X(030).
           05  PLC-USUCAR                     PIC X(030).
           05  PLC-VIA-CERT                   PIC X(030).
           05  PLC-VIST                       PIC X(030).
