      * WSD copybook for MODIFICADODS (auto-generated)
       01  MODIFICADODS.
           05  MODIFICADODS-ROWID             PIC X(018).
           05  MOD-ANO-CSV-RT-X               PIC X(004).
           05  MOD-ANO-CSV-X                  PIC X(004).
           05  MOD-CHASSI-X                   PIC X(021).
           05  MOD-COMPL-EIXO-X               PIC X(040).
           05  MOD-CSV-ACESS-X                PIC X(030).
           05  MOD-CSV-VISUAL-X               PIC X(030).
           05  MOD-DISTANC-EIXO-X             PIC X(030).
           05  MOD-DT-ACERVO-X                PIC X(010).
           05  MOD-DT-ACESS-COND-X            PIC X(010).
           05  MOD-DT-ACESS-PASS-X            PIC X(010).
           05  MOD-DT-ALONG-X                 PIC X(010).
           05  MOD-DT-ANOMODELO-X             PIC X(010).
           05  MOD-DT-CAB-DUPLA-X             PIC X(010).
           05  MOD-DT-CAB-ESTEND-X            PIC X(010).
           05  MOD-DT-CAP-CARGA-X             PIC X(010).
           05  MOD-DT-CAP-PAS-X               PIC X(010).
           05  MOD-DT-CARAPRE-X               PIC X(010).
           05  MOD-DT-CARROCERIA-X            PIC X(010).
           05  MOD-DT-CILINDRADA-X            PIC X(010).
           05  MOD-DT-CMT-X                   PIC X(010).
           05  MOD-DT-COMBUST-X               PIC X(010).
           05  MOD-DT-COMPL-EIXO-X            PIC X(010).
           05  MOD-DT-COR-X                   PIC X(010).
           05  MOD-DT-DUPL-PEDAL-X            PIC X(010).
           05  MOD-DT-ESPECIE-X               PIC X(010).
           05  MOD-DT-FILLER1-X               PIC X(010).
           05  MOD-DT-FREIO-X                 PIC X(010).
           05  MOD-DT-ILUM-SINAL-X            PIC X(010).
           05  MOD-DT-ILUMINA-X               PIC X(010).
           05  MOD-DT-INCLUSAO-X              PIC X(010).
           05  MOD-DT-INSULFILME-X            PIC X(010).
           05  MOD-DT-IPCH-X                  PIC X(010).
           05  MOD-DT-MARCA-X                 PIC X(010).
           05  MOD-DT-MUNCK-X                 PIC X(010).
           05  MOD-DT-NRO-EIXOS-X             PIC X(010).
           05  MOD-DT-OUTROS-X                PIC X(010).
           05  MOD-DT-PARACHOQUE-X            PIC X(010).
           05  MOD-DT-PBT-X                   PIC X(010).
           05  MOD-DT-PLATAFORMA-X            PIC X(010).
           05  MOD-DT-POTEN-CILI-X            PIC X(010).
           05  MOD-DT-POTENCIA-X              PIC X(010).
           05  MOD-DT-REBAIXAM-X              PIC X(010).
           05  MOD-DT-REENCARROC-X            PIC X(010).
           05  MOD-DT-RODAPNEU-X              PIC X(010).
           05  MOD-DT-SISEG-BASC-X            PIC X(010).
           05  MOD-DT-SIST-SEG-X              PIC X(010).
           05  MOD-DT-SUSP-PNEU-X             PIC X(010).
           05  MOD-DT-SUSP-X                  PIC X(010).
           05  MOD-DT-TANQUESUPL-X            PIC X(010).
           05  MOD-DT-TETO-SOLAR-X            PIC X(010).
           05  MOD-DT-TIPO-X                  PIC X(010).
           05  MOD-DT-TURBO-X                 PIC X(010).
           05  MOD-DT-VISUAL-X                PIC X(010).
           05  MOD-HR-INCLUSAO-X              PIC X(006).
           05  MOD-MUNIC-PLACA-X              PIC X(010).
           05  MOD-NRO-CSV-RT-X               PIC X(030).
           05  MOD-NRO-CSV-X                  PIC X(030).
           05  MOD-PLACA-MERC-X               PIC X(010).
           05  MOD-PLACA-X                    PIC X(010).
           05  MOD-TIPO-ACESS-X               PIC X(006).
           05  MOD-TRANSACAO-X                PIC X(030).
           05  MOD-USUARIO-X                  PIC X(008).
           05  MOD-VALOR-SUSP-X               PIC X(030).
           05  MOD-ANO-CSV-RT                 PIC 9(009).
           05  MOD-ANO-CSV                    PIC 9(009).
           05  MOD-CHASSI                     PIC X(021).
           05  MOD-COMPL-EIXO                 PIC X(040).
           05  MOD-CSV-ACESS                  PIC X(030).
           05  MOD-CSV-VISUAL                 PIC X(030).
           05  MOD-DISTANC-EIXO               PIC X(030).
           05  MOD-DT-ACERVO                  PIC 9(009).
           05  MOD-DT-ACESS-COND              PIC 9(009).
           05  MOD-DT-ACESS-PASS              PIC 9(009).
           05  MOD-DT-ALONG                   PIC 9(009).
           05  MOD-DT-ANOMODELO               PIC 9(009).
           05  MOD-DT-CAB-DUPLA               PIC 9(009).
           05  MOD-DT-CAB-ESTEND              PIC 9(009).
           05  MOD-DT-CAP-CARGA               PIC 9(009).
           05  MOD-DT-CAP-PAS                 PIC 9(009).
           05  MOD-DT-CARAPRE                 PIC 9(009).
           05  MOD-DT-CARROCERIA              PIC 9(009).
           05  MOD-DT-CILINDRADA              PIC 9(009).
           05  MOD-DT-CMT                     PIC 9(009).
           05  MOD-DT-COMBUST                 PIC 9(009).
           05  MOD-DT-COMPL-EIXO              PIC 9(009).
           05  MOD-DT-COR                     PIC 9(009).
           05  MOD-DT-DUPL-PEDAL              PIC 9(009).
           05  MOD-DT-ESPECIE                 PIC 9(009).
           05  MOD-DT-FILLER1                 PIC 9(009).
           05  MOD-DT-FREIO                   PIC 9(009).
           05  MOD-DT-ILUM-SINAL              PIC 9(009).
           05  MOD-DT-ILUMINA                 PIC 9(009).
           05  MOD-DT-INCLUSAO                PIC 9(009).
           05  MOD-DT-INSULFILME              PIC 9(009).
           05  MOD-DT-IPCH                    PIC 9(009).
           05  MOD-DT-MARCA                   PIC 9(009).
           05  MOD-DT-MUNCK                   PIC 9(009).
           05  MOD-DT-NRO-EIXOS               PIC 9(009).
           05  MOD-DT-OUTROS                  PIC 9(009).
           05  MOD-DT-PARACHOQUE              PIC 9(009).
           05  MOD-DT-PBT                     PIC 9(009).
           05  MOD-DT-PLATAFORMA              PIC 9(009).
           05  MOD-DT-POTEN-CILI              PIC 9(009).
           05  MOD-DT-POTENCIA                PIC 9(009).
           05  MOD-DT-REBAIXAM                PIC 9(009).
           05  MOD-DT-REENCARROC              PIC 9(009).
           05  MOD-DT-RODAPNEU                PIC 9(009).
           05  MOD-DT-SISEG-BASC              PIC 9(009).
           05  MOD-DT-SIST-SEG                PIC 9(009).
           05  MOD-DT-SUSP-PNEU               PIC 9(009).
           05  MOD-DT-SUSP                    PIC 9(009).
           05  MOD-DT-TANQUESUPL              PIC 9(009).
           05  MOD-DT-TETO-SOLAR              PIC 9(009).
           05  MOD-DT-TIPO                    PIC 9(009).
           05  MOD-DT-TURBO                   PIC 9(009).
           05  MOD-DT-VISUAL                  PIC 9(009).
           05  MOD-HR-INCLUSAO                PIC 9(009).
           05  MOD-MUNIC-PLACA                PIC X(010).
           05  MOD-NRO-CSV-RT                 PIC X(030).
           05  MOD-NRO-CSV                    PIC X(030).
           05  MOD-PLACA-MERC                 PIC X(010).
           05  MOD-PLACA                      PIC X(010).
           05  MOD-TIPO-ACESS                 PIC X(006).
           05  MOD-TRANSACAO                  PIC X(030).
           05  MOD-USUARIO                    PIC X(008).
           05  MOD-VALOR-SUSP                 PIC X(030).
