      * WSD copybook for GEVMODIFDS (auto-generated)
       01  GEVMODIFDS.
           05  GEVMODIFDS-ROWID               PIC X(018).
           05  GVM-ACESS-COND-X               PIC X(030).
           05  GVM-ACESS-PASS-X               PIC X(030).
           05  GVM-ALONG-CHASSI-X             PIC X(021).
           05  GVM-ANO-X                      PIC X(004).
           05  GVM-ANOMODELO-X                PIC X(004).
           05  GVM-AUTO-DIREC-X               PIC X(030).
           05  GVM-BLINDAGEM-X                PIC X(030).
           05  GVM-CAB-ESTEND-X               PIC X(030).
           05  GVM-CAB-SUPL-X                 PIC X(030).
           05  GVM-CABINE-X                   PIC X(030).
           05  GVM-CAP-CARGA-X                PIC X(030).
           05  GVM-CAP-PAS-X                  PIC X(030).
           05  GVM-CAP-VOL-TQ-X               PIC X(030).
           05  GVM-CARA-PRETA-X               PIC X(030).
           05  GVM-CARROCERIA-X               PIC X(030).
           05  GVM-CATEGORIA-X                PIC X(006).
           05  GVM-CERT-SEG-VEIC-X            PIC X(030).
           05  GVM-CHASSI-X                   PIC X(021).
           05  GVM-CILINDRADA-X               PIC X(030).
           05  GVM-CMT-X                      PIC X(030).
           05  GVM-COMBUSTIVEL-X              PIC X(006).
           05  GVM-COR-X                      PIC X(030).
           05  GVM-CSV-ACESS-X                PIC X(030).
           05  GVM-CSV-ANO-X                  PIC X(004).
           05  GVM-CSV-VISUAL-X               PIC X(030).
           05  GVM-DIRECIONAL-X               PIC X(030).
           05  GVM-DISTANC-EIXO-X             PIC X(030).
           05  GVM-DT-ATUALIZA-X              PIC X(010).
           05  GVM-DT-INCLUSAO-X              PIC X(010).
           05  GVM-DUPL-ILUM-X                PIC X(030).
           05  GVM-ENCURT-CHASSI-X            PIC X(021).
           05  GVM-ESPECIE-X                  PIC X(006).
           05  GVM-FILLER2-X                  PIC X(020).
           05  GVM-FILLER3-X                  PIC X(020).
           05  GVM-FILLER4-X                  PIC X(020).
           05  GVM-FILLER5-X                  PIC X(020).
           05  GVM-FREIO-X                    PIC X(030).
           05  GVM-HR-ATUALIZA-X              PIC X(006).
           05  GVM-HR-INCLUSAO-X              PIC X(006).
           05  GVM-ILUM-SINAL-X               PIC X(030).
           05  GVM-INSULFILME-X               PIC X(030).
           05  GVM-ISE-PARACH-X               PIC X(030).
           05  GVM-MARCA-X                    PIC X(006).
           05  GVM-MOD-VISUAL-X               PIC X(030).
           05  GVM-MUNIC-PLACA-X              PIC X(010).
           05  GVM-NRO-EIXOS-X                PIC X(030).
           05  GVM-NRO-FICHA-X                PIC X(030).
           05  GVM-PARACHOQUE-X               PIC X(030).
           05  GVM-PBT-X                      PIC X(030).
           05  GVM-PLACA-MERC-X               PIC X(010).
           05  GVM-PLACA-X                    PIC X(010).
           05  GVM-PLATAFORMA-X               PIC X(030).
           05  GVM-PNEUMATICA-X               PIC X(030).
           05  GVM-POTENCIA-X                 PIC X(030).
           05  GVM-QTDE-TQ-X                  PIC X(030).
           05  GVM-REBAIXAMENTO-X             PIC X(030).
           05  GVM-REENCARROC-X               PIC X(030).
           05  GVM-RODA-PNEU-X                PIC X(030).
           05  GVM-SIST-SEG-X                 PIC X(030).
           05  GVM-SUSP-PNEU-X                PIC X(030).
           05  GVM-SUSPENSAO-X                PIC X(030).
           05  GVM-TANQUESUPL-X               PIC X(030).
           05  GVM-TETO-SOLAR-X               PIC X(030).
           05  GVM-TIPO-ACESS-X               PIC X(006).
           05  GVM-TIPO-X                     PIC X(006).
           05  GVM-VI-SUSPENSAO-X             PIC X(030).
           05  GVM-ACESS-COND                 PIC X(030).
           05  GVM-ACESS-PASS                 PIC X(030).
           05  GVM-ALONG-CHASSI               PIC X(021).
           05  GVM-ANO                        PIC 9(009).
           05  GVM-ANOMODELO                  PIC 9(009).
           05  GVM-AUTO-DIREC                 PIC X(030).
           05  GVM-BLINDAGEM                  PIC X(030).
           05  GVM-CAB-ESTEND                 PIC X(030).
           05  GVM-CAB-SUPL                   PIC X(030).
           05  GVM-CABINE                     PIC X(030).
           05  GVM-CAP-CARGA                  PIC X(030).
           05  GVM-CAP-PAS                    PIC X(030).
           05  GVM-CAP-VOL-TQ                 PIC X(030).
           05  GVM-CARA-PRETA                 PIC X(030).
           05  GVM-CARROCERIA                 PIC X(030).
           05  GVM-CATEGORIA                  PIC X(006).
           05  GVM-CERT-SEG-VEIC              PIC X(030).
           05  GVM-CHASSI                     PIC X(021).
           05  GVM-CILINDRADA                 PIC X(030).
           05  GVM-CMT                        PIC X(030).
           05  GVM-COMBUSTIVEL                PIC X(006).
           05  GVM-COR                        PIC X(030).
           05  GVM-CSV-ACESS                  PIC X(030).
           05  GVM-CSV-ANO                    PIC 9(009).
           05  GVM-CSV-VISUAL                 PIC X(030).
           05  GVM-DIRECIONAL                 PIC X(030).
           05  GVM-DISTANC-EIXO               PIC X(030).
           05  GVM-DT-ATUALIZA                PIC 9(009).
           05  GVM-DT-INCLUSAO                PIC 9(009).
           05  GVM-DUPL-ILUM                  PIC X(030).
           05  GVM-ENCURT-CHASSI              PIC X(021).
           05  GVM-ESPECIE                    PIC X(006).
           05  GVM-FILLER2                    PIC X(020).
           05  GVM-FILLER3                    PIC X(020).
           05  GVM-FILLER4                    PIC X(020).
           05  GVM-FILLER5                    PIC X(020).
           05  GVM-FREIO                      PIC X(030).
           05  GVM-HR-ATUALIZA                PIC 9(009).
           05  GVM-HR-INCLUSAO                PIC 9(009).
           05  GVM-ILUM-SINAL                 PIC X(030).
           05  GVM-INSULFILME                 PIC X(030).
           05  GVM-ISE-PARACH                 PIC X(030).
           05  GVM-MARCA                      PIC X(006).
           05  GVM-MOD-VISUAL                 PIC X(030).
           05  GVM-MUNIC-PLACA                PIC X(010).
           05  GVM-NRO-EIXOS                  PIC X(030).
           05  GVM-NRO-FICHA                  PIC X(030).
           05  GVM-PARACHOQUE                 PIC X(030).
           05  GVM-PBT                        PIC X(030).
           05  GVM-PLACA-MERC                 PIC X(010).
           05  GVM-PLACA                      PIC X(010).
           05  GVM-PLATAFORMA                 PIC X(030).
           05  GVM-PNEUMATICA                 PIC X(030).
           05  GVM-POTENCIA                   PIC X(030).
           05  GVM-QTDE-TQ                    PIC X(030).
           05  GVM-REBAIXAMENTO               PIC X(030).
           05  GVM-REENCARROC                 PIC X(030).
           05  GVM-RODA-PNEU                  PIC X(030).
           05  GVM-SIST-SEG                   PIC X(030).
           05  GVM-SUSP-PNEU                  PIC X(030).
           05  GVM-SUSPENSAO                  PIC X(030).
           05  GVM-TANQUESUPL                 PIC X(030).
           05  GVM-TETO-SOLAR                 PIC X(030).
           05  GVM-TIPO-ACESS                 PIC X(006).
           05  GVM-TIPO                       PIC X(006).
           05  GVM-VI-SUSPENSAO               PIC X(030).
