      * WSD copybook for LACRACAODS (auto-generated)
       01  LACRACAODS.
           05  LACRACAODS-ROWID               PIC X(018).
           05  LAC-BIN-DT-ENVIO-X             PIC X(010).
           05  LAC-BIN-HR-ENVIO-X             PIC X(006).
           05  LAC-BIN-ID-AUTOR-X             PIC X(020).
           05  LAC-BIN-MOTIVO-X               PIC X(020).
           05  LAC-BIN-OFICIAL-X              PIC X(010).
           05  LAC-BIN-RETORNO-X              PIC X(020).
           05  LAC-BIN-TIPO-X                 PIC X(006).
           05  LAC-BIN-US-ENVIO-X             PIC X(020).
           05  LAC-CATEGORIA-X                PIC X(006).
           05  LAC-CPF-CNPJ-X                 PIC X(011).
           05  LAC-CPF-LACRE-X                PIC X(011).
           05  LAC-DT-EMISSAO-X               PIC X(010).
           05  LAC-DT-INCLUSAO-X              PIC X(010).
           05  LAC-DT-LACRACAO-X              PIC X(010).
           05  LAC-ESPECIE-X                  PIC X(006).
           05  LAC-FORNECEDOR-X               PIC X(030).
           05  LAC-HR-EMISSAO-X               PIC X(006).
           05  LAC-HR-INCLUSAO-X              PIC X(006).
           05  LAC-HR-LACRACAO-X              PIC X(006).
           05  LAC-MOTIVO-X                   PIC X(030).
           05  LAC-MUNIC-DEST-X               PIC X(005).
           05  LAC-MUNICIPIO-X                PIC X(005).
           05  LAC-NRO-LACRE-X                PIC X(030).
           05  LAC-OPCAO-X                    PIC X(030).
           05  LAC-PLACA-MERC-X               PIC X(010).
           05  LAC-PLACA-X                    PIC X(010).
           05  LAC-PRESTADORA-X               PIC X(030).
           05  LAC-REGIAO-X                   PIC X(030).
           05  LAC-RENAVAM-X                  PIC X(011).
           05  LAC-SENHA-X                    PIC X(030).
           05  LAC-TIPO-COD-X                 PIC X(006).
           05  LAC-TIPO-X                     PIC X(006).
           05  LAC-UF-DEST-X                  PIC X(002).
           05  LAC-UNIDADE-AUTORIZ-X          PIC X(030).
           05  LAC-USU-EMISSAO-X              PIC X(008).
           05  LAC-USU-LACRE-X                PIC X(008).
           05  LAC-VALOR-X                    PIC X(030).
           05  LAC-BIN-DT-ENVIO               PIC 9(009).
           05  LAC-BIN-HR-ENVIO               PIC 9(009).
           05  LAC-BIN-ID-AUTOR               PIC X(020).
           05  LAC-BIN-MOTIVO                 PIC X(020).
           05  LAC-BIN-OFICIAL                PIC X(010).
           05  LAC-BIN-RETORNO                PIC X(020).
           05  LAC-BIN-TIPO                   PIC X(006).
           05  LAC-BIN-US-ENVIO               PIC X(020).
           05  LAC-CATEGORIA                  PIC X(006).
           05  LAC-CPF-CNPJ                   PIC X(011).
           05  LAC-CPF-LACRE                  PIC X(011).
           05  LAC-DT-EMISSAO                 PIC 9(009).
           05  LAC-DT-INCLUSAO                PIC 9(009).
           05  LAC-DT-LACRACAO                PIC 9(009).
           05  LAC-ESPECIE                    PIC X(006).
           05  LAC-FORNECEDOR                 PIC X(030).
           05  LAC-HR-EMISSAO                 PIC 9(009).
           05  LAC-HR-INCLUSAO                PIC 9(009).
           05  LAC-HR-LACRACAO                PIC 9(009).
           05  LAC-MOTIVO                     PIC X(030).
           05  LAC-MUNIC-DEST                 PIC X(005).
           05  LAC-MUNICIPIO                  PIC 9(009).
           05  LAC-NRO-LACRE                  PIC X(030).
           05  LAC-OPCAO                      PIC X(030).
           05  LAC-PLACA-MERC                 PIC X(010).
           05  LAC-PLACA                      PIC X(010).
           05  LAC-PRESTADORA                 PIC X(030).
           05  LAC-REGIAO                     PIC X(030).
           05  LAC-RENAVAM                    PIC X(011).
           05  LAC-SENHA                      PIC X(030).
           05  LAC-TIPO-COD                   PIC X(006).
           05  LAC-TIPO                       PIC X(006).
           05  LAC-UF-DEST                    PIC X(002).
           05  LAC-UNIDADE-AUTORIZ            PIC X(030).
           05  LAC-USU-EMISSAO                PIC X(008).
           05  LAC-USU-LACRE                  PIC X(008).
           05  LAC-VALOR                      PIC X(030).
