      * WSD copybook for USUARIODS (auto-generated)
       01  USUARIODS.
           05  USUARIODS-ROWID                PIC X(018).
           05  USU-COD-DGSOLEXC-X             PIC X(006).
           05  USU-COD-DGSOLINI-X             PIC X(006).
           05  USU-COD-LOCAL-X                PIC X(006).
           05  USU-COD-NUMSOEXC-X             PIC X(006).
           05  USU-COD-NUMSOINI-X             PIC X(006).
           05  USU-DATAALT-X                  PIC X(010).
           05  USU-DATACAD-X                  PIC X(010).
           05  USU-DDD-X                      PIC X(010).
           05  USU-EMAIL-X                    PIC X(008).
           05  USU-FILLER1-X                  PIC X(020).
           05  USU-FINALIDADE-X               PIC X(008).
           05  USU-FLAG-X                     PIC X(008).
           05  USU-FONE-CELULAR-X             PIC X(008).
           05  USU-HORAEXC-X                  PIC X(006).
           05  USU-HORAINC-X                  PIC X(006).
           05  USU-LASTACES-DATE-X            PIC X(010).
           05  USU-LASTACES-HORA-X            PIC X(006).
           05  USU-MOTIVO1-X                  PIC X(008).
           05  USU-MOTIVO2-X                  PIC X(008).
           05  USU-NOME-X                     PIC X(040).
           05  USU-OAS-ANO-X                  PIC X(004).
           05  USU-OAS-NUM-X                  PIC X(008).
           05  USU-PEDIDO-X                   PIC X(008).
           05  USU-QTTRANS-X                  PIC X(008).
           05  USU-RG-X                       PIC X(008).
           05  USU-SEGURANCA-X                PIC X(008).
           05  USU-SUBLOCAL-X                 PIC X(008).
           05  USU-TAMANHO-X                  PIC X(008).
           05  USU-USERCODE-X                 PIC X(008).
           05  USU-USERSOLICEX-X              PIC X(008).
           05  USU-USERSOLICIN-X              PIC X(008).
           05  USU-COD-DGSOLEXC               PIC 9(009).
           05  USU-COD-DGSOLINI               PIC 9(009).
           05  USU-COD-LOCAL                  PIC 9(009).
           05  USU-COD-NUMSOEXC               PIC 9(009).
           05  USU-COD-NUMSOINI               PIC 9(009).
           05  USU-DATAALT                    PIC X(010).
           05  USU-DATACAD                    PIC X(010).
           05  USU-DDD                        PIC X(010).
           05  USU-EMAIL                      PIC X(008).
           05  USU-FILLER1                    PIC X(020).
           05  USU-FINALIDADE                 PIC X(008).
           05  USU-FLAG                       PIC X(008).
           05  USU-FONE-CELULAR               PIC X(008).
           05  USU-HORAEXC                    PIC X(006).
           05  USU-HORAINC                    PIC X(006).
           05  USU-LASTACES-DATE              PIC X(010).
           05  USU-LASTACES-HORA              PIC X(006).
           05  USU-MOTIVO1                    PIC X(008).
           05  USU-MOTIVO2                    PIC X(008).
           05  USU-NOME                       PIC X(040).
           05  USU-OAS-ANO                    PIC 9(009).
           05  USU-OAS-NUM                    PIC X(008).
           05  USU-PEDIDO                     PIC X(008).
           05  USU-QTTRANS                    PIC X(008).
           05  USU-RG                         PIC X(008).
           05  USU-SEGURANCA                  PIC X(008).
           05  USU-SUBLOCAL                   PIC X(008).
           05  USU-TAMANHO                    PIC X(008).
           05  USU-USERCODE                   PIC X(008).
           05  USU-USERSOLICEX                PIC X(008).
           05  USU-USERSOLICIN                PIC X(008).
