      * WSD copybook for COMVENDHISDS (auto-generated)
       01  COMVENDHISDS.
           05  COMVENDHISDS-ROWID             PIC X(018).
           05  CVH-ANO-FABR-X                 PIC X(004).
           05  CVH-ANO-MOD-X                  PIC X(004).
           05  CVH-ANO-X                      PIC X(004).
           05  CVH-BAIRRO-CART-X              PIC X(040).
           05  CVH-BAIRRO-CARTV-X             PIC X(040).
           05  CVH-BAIRRO-CV-X                PIC X(040).
           05  CVH-CD-SEG-CRV-X               PIC X(006).
           05  CVH-CEP-END-CART-X             PIC X(008).
           05  CVH-CEP-END-CARTC-X            PIC X(008).
           05  CVH-CEP-END-CV-X               PIC X(008).
           05  CVH-CHASSI-X                   PIC X(021).
           05  CVH-CNPJ-SEG-X                 PIC X(014).
           05  CVH-COMP-END-CART-X            PIC X(030).
           05  CVH-COMPEND-CARTC-X            PIC X(030).
           05  CVH-COMPL-CV-X                 PIC X(040).
           05  CVH-CPF-CGC-CV-X               PIC X(014).
           05  CVH-CPF-USUPROT-X              PIC X(011).
           05  CVH-DDD-CART-X                 PIC X(010).
           05  CVH-DDD-CARTC-X                PIC X(010).
           05  CVH-DOCTO-CV-X                 PIC X(030).
           05  CVH-DOCTO-INFORM-X             PIC X(030).
           05  CVH-DT-ATUALIZ-X               PIC X(010).
           05  CVH-DT-AVERBACAO-X             PIC X(010).
           05  CVH-DT-BIN-X                   PIC X(010).
           05  CVH-DT-CANC-X                  PIC X(010).
           05  CVH-DT-DOCTS-X                 PIC X(010).
           05  CVH-DT-EMIS-CRV-X              PIC X(010).
           05  CVH-DT-EXCL-X                  PIC X(010).
           05  CVH-DT-HISTORICO-X             PIC X(010).
           05  CVH-DT-INCLUSAO-X              PIC X(010).
           05  CVH-DT-LEILAO-X                PIC X(010).
           05  CVH-DT-NFISCAL-X               PIC X(010).
           05  CVH-DT-PROT-X                  PIC X(010).
           05  CVH-DT-REC-FIRMA-X             PIC X(010).
           05  CVH-DT-TRANSF-X                PIC X(010).
           05  CVH-DT-VENDA-X                 PIC X(010).
           05  CVH-END-CART-X                 PIC X(030).
           05  CVH-END-CARTC-X                PIC X(030).
           05  CVH-ENDERECO-CV-X              PIC X(040).
           05  CVH-ENTR-DADOS-X               PIC X(030).
           05  CVH-FINANC-X                   PIC X(030).
           05  CVH-FLAG-MOT-X                 PIC X(030).
           05  CVH-FOL-COMP-X                 PIC X(030).
           05  CVH-FOL-VEND-X                 PIC X(030).
           05  CVH-HR-CANC-X                  PIC X(006).
           05  CVH-HR-HISTORICO-X             PIC X(006).
           05  CVH-HR-INCLUSAO-X              PIC X(006).
           05  CVH-ID-ASSINAT-X               PIC X(030).
           05  CVH-IDENT-CART-X               PIC X(030).
           05  CVH-IDENT-CARTC-X              PIC X(030).
           05  CVH-IDENT-PROPR-X              PIC X(030).
           05  CVH-LIV-COMP-X                 PIC X(030).
           05  CVH-LIV-VEND-X                 PIC X(030).
           05  CVH-MOT-CANC-X                 PIC X(030).
           05  CVH-MUN-END-CV-X               PIC X(005).
           05  CVH-MUN-VENDA-X                PIC X(005).
           05  CVH-MUNIC-CART-X               PIC X(005).
           05  CVH-MUNIC-CARTC-X              PIC X(005).
           05  CVH-MUNICIPIO-X                PIC X(005).
           05  CVH-NOME-CART-X                PIC X(040).
           05  CVH-NOME-CARTC-X               PIC X(040).
           05  CVH-NOME-CV-X                  PIC X(040).
           05  CVH-NOME-INFORM-X              PIC X(040).
           05  CVH-NOME-PROPR-X               PIC X(040).
           05  CVH-NRO-CRV-X                  PIC X(030).
           05  CVH-NRO-END-CART-X             PIC X(030).
           05  CVH-NRO-END-CARTC-X            PIC X(030).
           05  CVH-NRO-FICHA-X                PIC X(030).
           05  CVH-NRO-IDENT-CV-X             PIC X(030).
           05  CVH-NRO-IMOVEL-CV-X            PIC X(030).
           05  CVH-NRO-VIA-CRV-X              PIC X(030).
           05  CVH-PLACA-MERC-X               PIC X(010).
           05  CVH-PLACA-X                    PIC X(010).
           05  CVH-PROTOC-FAZ-X               PIC X(010).
           05  CVH-RENAVAM-X                  PIC X(011).
           05  CVH-RET-BIN-X                  PIC X(030).
           05  CVH-SSP-DESP-X                 PIC X(030).
           05  CVH-TEL-CART-X                 PIC X(030).
           05  CVH-TEL-CARTC-X                PIC X(030).
           05  CVH-TIPO-DOCTO-X               PIC X(006).
           05  CVH-TP-DOC-CART-X              PIC X(030).
           05  CVH-TP-DOC-CARTC-X             PIC X(030).
           05  CVH-UF-CART-X                  PIC X(002).
           05  CVH-UF-CARTC-X                 PIC X(002).
           05  CVH-UF-CV-X                    PIC X(002).
           05  CVH-UF-EMISSAO-X               PIC X(002).
           05  CVH-USU-EXCL-X                 PIC X(008).
           05  CVH-USU-PROT-X                 PIC X(008).
           05  CVH-USUARIO-X                  PIC X(008).
           05  CVH-ANO-FABR                   PIC 9(009).
           05  CVH-ANO-MOD                    PIC 9(009).
           05  CVH-ANO                        PIC 9(009).
           05  CVH-BAIRRO-CART                PIC X(040).
           05  CVH-BAIRRO-CARTV               PIC X(040).
           05  CVH-BAIRRO-CV                  PIC X(040).
           05  CVH-CD-SEG-CRV                 PIC X(006).
           05  CVH-CEP-END-CART               PIC X(008).
           05  CVH-CEP-END-CARTC              PIC X(008).
           05  CVH-CEP-END-CV                 PIC X(008).
           05  CVH-CHASSI                     PIC X(021).
           05  CVH-CNPJ-SEG                   PIC X(014).
           05  CVH-COMP-END-CART              PIC X(030).
           05  CVH-COMPEND-CARTC              PIC X(030).
           05  CVH-COMPL-CV                   PIC X(040).
           05  CVH-CPF-CGC-CV                 PIC X(014).
           05  CVH-CPF-USUPROT                PIC X(011).
           05  CVH-DDD-CART                   PIC X(010).
           05  CVH-DDD-CARTC                  PIC X(010).
           05  CVH-DOCTO-CV                   PIC X(030).
           05  CVH-DOCTO-INFORM               PIC X(030).
           05  CVH-DT-ATUALIZ                 PIC 9(009).
           05  CVH-DT-AVERBACAO               PIC 9(009).
           05  CVH-DT-BIN                     PIC 9(009).
           05  CVH-DT-CANC                    PIC 9(009).
           05  CVH-DT-DOCTS                   PIC 9(009).
           05  CVH-DT-EMIS-CRV                PIC 9(009).
           05  CVH-DT-EXCL                    PIC 9(009).
           05  CVH-DT-HISTORICO               PIC 9(009).
           05  CVH-DT-INCLUSAO                PIC 9(009).
           05  CVH-DT-LEILAO                  PIC 9(009).
           05  CVH-DT-NFISCAL                 PIC 9(009).
           05  CVH-DT-PROT                    PIC 9(009).
           05  CVH-DT-REC-FIRMA               PIC 9(009).
           05  CVH-DT-TRANSF                  PIC 9(009).
           05  CVH-DT-VENDA                   PIC 9(009).
           05  CVH-END-CART                   PIC X(030).
           05  CVH-END-CARTC                  PIC X(030).
           05  CVH-ENDERECO-CV                PIC X(040).
           05  CVH-ENTR-DADOS                 PIC X(030).
           05  CVH-FINANC                     PIC X(030).
           05  CVH-FLAG-MOT                   PIC X(030).
           05  CVH-FOL-COMP                   PIC X(030).
           05  CVH-FOL-VEND                   PIC X(030).
           05  CVH-HR-CANC                    PIC 9(009).
           05  CVH-HR-HISTORICO               PIC 9(009).
           05  CVH-HR-INCLUSAO                PIC 9(009).
           05  CVH-ID-ASSINAT                 PIC X(030).
           05  CVH-IDENT-CART                 PIC X(030).
           05  CVH-IDENT-CARTC                PIC X(030).
           05  CVH-IDENT-PROPR                PIC X(030).
           05  CVH-LIV-COMP                   PIC X(030).
           05  CVH-LIV-VEND                   PIC X(030).
           05  CVH-MOT-CANC                   PIC X(030).
           05  CVH-MUN-END-CV                 PIC X(005).
           05  CVH-MUN-VENDA                  PIC X(005).
           05  CVH-MUNIC-CART                 PIC X(005).
           05  CVH-MUNIC-CARTC                PIC X(005).
           05  CVH-MUNICIPIO                  PIC 9(009).
           05  CVH-NOME-CART                  PIC X(040).
           05  CVH-NOME-CARTC                 PIC X(040).
           05  CVH-NOME-CV                    PIC X(040).
           05  CVH-NOME-INFORM                PIC X(040).
           05  CVH-NOME-PROPR                 PIC X(040).
           05  CVH-NRO-CRV                    PIC X(030).
           05  CVH-NRO-END-CART               PIC X(030).
           05  CVH-NRO-END-CARTC              PIC X(030).
           05  CVH-NRO-FICHA                  PIC X(030).
           05  CVH-NRO-IDENT-CV               PIC X(030).
           05  CVH-NRO-IMOVEL-CV              PIC X(030).
           05  CVH-NRO-VIA-CRV                PIC X(030).
           05  CVH-PLACA-MERC                 PIC X(010).
           05  CVH-PLACA                      PIC X(010).
           05  CVH-PROTOC-FAZ                 PIC X(010).
           05  CVH-RENAVAM                    PIC X(011).
           05  CVH-RET-BIN                    PIC X(030).
           05  CVH-SSP-DESP                   PIC X(030).
           05  CVH-TEL-CART                   PIC X(030).
           05  CVH-TEL-CARTC                  PIC X(030).
           05  CVH-TIPO-DOCTO                 PIC X(006).
           05  CVH-TP-DOC-CART                PIC X(030).
           05  CVH-TP-DOC-CARTC               PIC X(030).
           05  CVH-UF-CART                    PIC X(002).
           05  CVH-UF-CARTC                   PIC X(002).
           05  CVH-UF-CV                      PIC X(002).
           05  CVH-UF-EMISSAO                 PIC X(002).
           05  CVH-USU-EXCL                   PIC X(008).
           05  CVH-USU-PROT                   PIC X(008).
           05  CVH-USUARIO                    PIC X(008).
