      * WSD copybook for QUEIXADS (auto-generated)
       01  QUEIXADS.
           05  QUEIXADS-ROWID                 PIC X(018).
           05  QXA-ANO-BOQ-X                  PIC X(004).
           05  QXA-ANOFABR-X                  PIC X(004).
           05  QXA-ANOMOD-X                   PIC X(004).
           05  QXA-BAIRRO-X                   PIC X(040).
           05  QXA-BO-QUEIXA-X                PIC X(012).
           05  QXA-BOSPJQ-ANO-X               PIC X(004).
           05  QXA-BOSPJQ-COD-X               PIC X(012).
           05  QXA-CEP-X                      PIC X(008).
           05  QXA-CHASSIS-X                  PIC X(021).
           05  QXA-COMPL-X                    PIC X(040).
           05  QXA-COR-X                      PIC X(030).
           05  QXA-DDD-X                      PIC X(010).
           05  QXA-DELEG-QUEIXA-X             PIC X(030).
           05  QXA-DOC-VITIMA-X               PIC X(030).
           05  QXA-DT-CADQUE-X                PIC X(010).
           05  QXA-DT-QUEIXA-X                PIC X(010).
           05  QXA-FILLER1-X                  PIC X(020).
           05  QXA-FILLER2-X                  PIC X(020).
           05  QXA-FILLER3-X                  PIC X(020).
           05  QXA-FILLER4-X                  PIC X(020).
           05  QXA-FILLER5-X                  PIC X(020).
           05  QXA-FILLER6-X                  PIC X(020).
           05  QXA-FILLER7-X                  PIC X(020).
           05  QXA-FILLER8-X                  PIC X(020).
           05  QXA-HR-CADQUE-X                PIC X(006).
           05  QXA-HR-QUEIXA-X                PIC X(006).
           05  QXA-IPANO-X                    PIC X(030).
           05  QXA-IPNUM-X                    PIC X(030).
           05  QXA-LOGRADOURO-X               PIC X(040).
           05  QXA-MARCA-X                    PIC X(006).
           05  QXA-MUNIC-END-X                PIC X(005).
           05  QXA-MUNIC-QUEIXA-X             PIC X(005).
           05  QXA-MUNICIPIO-X                PIC X(005).
           05  QXA-NOME-VITIMA-X              PIC X(040).
           05  QXA-NUMERO-END-X               PIC X(030).
           05  QXA-PLACA-X                    PIC X(010).
           05  QXA-PLACAX-X                   PIC X(010).
           05  QXA-RAMAL-X                    PIC X(010).
           05  QXA-RENAVAM-X                  PIC X(011).
           05  QXA-TELEFONE-X                 PIC X(010).
           05  QXA-TIPO-DECL-X                PIC X(006).
           05  QXA-TIPO-DOC-X                 PIC X(006).
           05  QXA-TIPO-X                     PIC X(006).
           05  QXA-UF-BOQ-X                   PIC X(002).
           05  QXA-UF-JURISD-X                PIC X(002).
           05  QXA-USU-QUEIXA-X               PIC X(008).
           05  QXA-ANO-BOQ                    PIC 9(009).
           05  QXA-ANOFABR                    PIC 9(009).
           05  QXA-ANOMOD                     PIC 9(009).
           05  QXA-BAIRRO                     PIC X(040).
           05  QXA-BO-QUEIXA                  PIC X(012).
           05  QXA-BOSPJQ-ANO                 PIC 9(009).
           05  QXA-BOSPJQ-COD                 PIC X(012).
           05  QXA-CEP                        PIC X(008).
           05  QXA-CHASSIS                    PIC X(021).
           05  QXA-COMPL                      PIC X(040).
           05  QXA-COR                        PIC X(030).
           05  QXA-DDD                        PIC X(010).
           05  QXA-DELEG-QUEIXA               PIC X(030).
           05  QXA-DOC-VITIMA                 PIC X(030).
           05  QXA-DT-CADQUE                  PIC 9(009).
           05  QXA-DT-QUEIXA                  PIC 9(009).
           05  QXA-FILLER1                    PIC X(020).
           05  QXA-FILLER2                    PIC X(020).
           05  QXA-FILLER3                    PIC X(020).
           05  QXA-FILLER4                    PIC X(020).
           05  QXA-FILLER5                    PIC X(020).
           05  QXA-FILLER6                    PIC X(020).
           05  QXA-FILLER7                    PIC X(020).
           05  QXA-FILLER8                    PIC X(020).
           05  QXA-HR-CADQUE                  PIC 9(009).
           05  QXA-HR-QUEIXA                  PIC 9(009).
           05  QXA-IPANO                      PIC X(030).
           05  QXA-IPNUM                      PIC X(030).
           05  QXA-LOGRADOURO                 PIC X(040).
           05  QXA-MARCA                      PIC X(006).
           05  QXA-MUNIC-END                  PIC X(005).
           05  QXA-MUNIC-QUEIXA               PIC X(005).
           05  QXA-MUNICIPIO                  PIC 9(009).
           05  QXA-NOME-VITIMA                PIC X(040).
           05  QXA-NUMERO-END                 PIC X(030).
           05  QXA-PLACA                      PIC X(010).
           05  QXA-PLACAX                     PIC X(010).
           05  QXA-RAMAL                      PIC X(010).
           05  QXA-RENAVAM                    PIC X(011).
           05  QXA-TELEFONE                   PIC X(010).
           05  QXA-TIPO-DECL                  PIC X(006).
           05  QXA-TIPO-DOC                   PIC X(006).
           05  QXA-TIPO                       PIC X(006).
           05  QXA-UF-BOQ                     PIC X(002).
           05  QXA-UF-JURISD                  PIC X(002).
           05  QXA-USU-QUEIXA                 PIC X(008).
