      * WSD copybook for GRAVAMECONTRDS (auto-generated)
       01  GRAVAMECONTRDS.
           05  GRAVAMECONTRDS-ROWID           PIC X(018).
           05  GRC-ANOFABR-X                  PIC X(004).
           05  GRC-ANOMOD-X                   PIC X(004).
           05  GRC-ASSINELETG785-X            PIC X(030).
           05  GRC-CD-AGENTE-X                PIC X(006).
           05  GRC-CGC-AGENTE-X               PIC X(014).
           05  GRC-CHASSI-REM-X               PIC X(021).
           05  GRC-CHASSI-X                   PIC X(021).
           05  GRC-CPF-CGC-DEVED-X            PIC X(014).
           05  GRC-DT-ADITCONTR-X             PIC X(010).
           05  GRC-DT-INCLUSAO-X              PIC X(010).
           05  GRC-DT-LIBERCRED-X             PIC X(010).
           05  GRC-DT-VENCPAR1-X              PIC X(010).
           05  GRC-DT-VENCULTPAR-X            PIC X(010).
           05  GRC-DT-VIG-CONTR-X             PIC X(010).
           05  GRC-FLAG-TRXG785-X             PIC X(030).
           05  GRC-HR-INCLUSAO-X              PIC X(006).
           05  GRC-INDICES-X                  PIC X(030).
           05  GRC-IOF-X                      PIC X(030).
           05  GRC-MUN-LIBERCRED-X            PIC X(005).
           05  GRC-NOME-AGENTE-X              PIC X(040).
           05  GRC-NOME-DEVED-X               PIC X(040).
           05  GRC-NUM-ADITCONTR-X            PIC X(010).
           05  GRC-NUM-CONTR-X                PIC X(010).
           05  GRC-NUM-COTACONSO-X            PIC X(010).
           05  GRC-NUM-GRUPCONSO-X            PIC X(010).
           05  GRC-NUM-REGIADIT-X             PIC X(010).
           05  GRC-NUM-REGICONTR-X            PIC X(010).
           05  GRC-NUM-RESTRICAO-X            PIC X(010).
           05  GRC-OPERADORA-X                PIC X(030).
           05  GRC-PLACA-X                    PIC X(010).
           05  GRC-QTD-PARC-X                 PIC X(010).
           05  GRC-RENAVAM-X                  PIC X(011).
           05  GRC-TAXA-CONTR-X               PIC X(030).
           05  GRC-TAXA-JUROANO-X             PIC X(030).
           05  GRC-TAXA-JUROMES-X             PIC X(030).
           05  GRC-TAXA-MORA-DIA-X            PIC X(030).
           05  GRC-TIPO-RESTR-X               PIC X(006).
           05  GRC-TOTAL-FINANC-X             PIC X(030).
           05  GRC-TX-JURO-MULTA-X            PIC X(030).
           05  GRC-UF-LIBERCRED-X             PIC X(002).
           05  GRC-UFLICEN-X                  PIC X(030).
           05  GRC-UFPLACA-X                  PIC X(010).
           05  GRC-VALOR-PAR-X                PIC X(030).
           05  GRC-ANOFABR                    PIC 9(009).
           05  GRC-ANOMOD                     PIC 9(009).
           05  GRC-ASSINELETG785              PIC X(030).
           05  GRC-CD-AGENTE                  PIC X(006).
           05  GRC-CGC-AGENTE                 PIC X(014).
           05  GRC-CHASSI-REM                 PIC X(021).
           05  GRC-CHASSI                     PIC X(021).
           05  GRC-CPF-CGC-DEVED              PIC X(014).
           05  GRC-DT-ADITCONTR               PIC 9(009).
           05  GRC-DT-INCLUSAO                PIC 9(009).
           05  GRC-DT-LIBERCRED               PIC 9(009).
           05  GRC-DT-VENCPAR1                PIC 9(009).
           05  GRC-DT-VENCULTPAR              PIC 9(009).
           05  GRC-DT-VIG-CONTR               PIC 9(009).
           05  GRC-FLAG-TRXG785               PIC X(030).
           05  GRC-HR-INCLUSAO                PIC 9(009).
           05  GRC-INDICES                    PIC X(030).
           05  GRC-IOF                        PIC X(030).
           05  GRC-MUN-LIBERCRED              PIC X(005).
           05  GRC-NOME-AGENTE                PIC X(040).
           05  GRC-NOME-DEVED                 PIC X(040).
           05  GRC-NUM-ADITCONTR              PIC 9(009).
           05  GRC-NUM-CONTR                  PIC 9(009).
           05  GRC-NUM-COTACONSO              PIC 9(009).
           05  GRC-NUM-GRUPCONSO              PIC 9(009).
           05  GRC-NUM-REGIADIT               PIC 9(009).
           05  GRC-NUM-REGICONTR              PIC 9(009).
           05  GRC-NUM-RESTRICAO              PIC 9(009).
           05  GRC-OPERADORA                  PIC X(030).
           05  GRC-PLACA                      PIC X(010).
           05  GRC-QTD-PARC                   PIC 9(009).
           05  GRC-RENAVAM                    PIC X(011).
           05  GRC-TAXA-CONTR                 PIC X(030).
           05  GRC-TAXA-JUROANO               PIC X(030).
           05  GRC-TAXA-JUROMES               PIC X(030).
           05  GRC-TAXA-MORA-DIA              PIC X(030).
           05  GRC-TIPO-RESTR                 PIC X(006).
           05  GRC-TOTAL-FINANC               PIC X(030).
           05  GRC-TX-JURO-MULTA              PIC X(030).
           05  GRC-UF-LIBERCRED               PIC X(002).
           05  GRC-UFLICEN                    PIC X(030).
           05  GRC-UFPLACA                    PIC X(010).
           05  GRC-VALOR-PAR                  PIC X(030).
