      * WSD copybook for GEVERDS (auto-generated)
       01  GEVERDS.
           05  GEVERDS-ROWID                  PIC X(018).
           05  GER-ANO-X                      PIC X(004).
           05  GER-ANOFABR-X                  PIC X(004).
           05  GER-ANOMOD-X                   PIC X(004).
           05  GER-ARREND-FIN-X               PIC X(030).
           05  GER-AUT-DIGITAL-X              PIC X(030).
           05  GER-AUT-EMPL-X                 PIC X(030).
           05  GER-BAIRRO-X                   PIC X(040).
           05  GER-CAP-CAR-X                  PIC X(030).
           05  GER-CAP-PAS-X                  PIC X(030).
           05  GER-CARROCERIA-X               PIC X(030).
           05  GER-CATEGORIA-X                PIC X(006).
           05  GER-CEP-ENDPROP-X              PIC X(008).
           05  GER-CHASSI-REM-X               PIC X(021).
           05  GER-CHASSI-X                   PIC X(021).
           05  GER-CHAVEACESS-NF-X            PIC X(030).
           05  GER-CILINDRADA-X               PIC X(030).
           05  GER-CMT-X                      PIC X(030).
           05  GER-COMBUSTIVEL-X              PIC X(006).
           05  GER-COMODATO-X                 PIC X(030).
           05  GER-COMPL-X                    PIC X(040).
           05  GER-COMTROP5-EXCL-X            PIC X(030).
           05  GER-CONFERENTE-X               PIC X(030).
           05  GER-COR-X                      PIC X(030).
           05  GER-CPF-CGC-X                  PIC X(014).
           05  GER-CPF-USUSTAT-X              PIC X(011).
           05  GER-DATA-VENDA-X               PIC X(010).
           05  GER-DESP-SSP-X                 PIC X(030).
           05  GER-DIGITADOR-X                PIC X(030).
           05  GER-DT-ALTERACAO-X             PIC X(010).
           05  GER-DT-CONFERENTE-X            PIC X(010).
           05  GER-DT-DIGITADOR-X             PIC X(010).
           05  GER-DT-EMIS-NF-X               PIC X(010).
           05  GER-DT-INCLUSAO-X              PIC X(010).
           05  GER-DT-REC-DOCTS-X             PIC X(010).
           05  GER-DT-STAT-ECRV-X             PIC X(010).
           05  GER-DT-VIG-CONTR-X             PIC X(010).
           05  GER-DT-VIST-X                  PIC X(010).
           05  GER-ENDERECO-X                 PIC X(040).
           05  GER-ESPECIE-X                  PIC X(006).
           05  GER-ESPELHO-ANT-X              PIC X(030).
           05  GER-FILLER1-X                  PIC X(020).
           05  GER-FILLER2-X                  PIC X(020).
           05  GER-FILLER3-X                  PIC X(020).
           05  GER-FILLER4-X                  PIC X(020).
           05  GER-FILLER5-X                  PIC X(020).
           05  GER-FINANC-X                   PIC X(030).
           05  GER-HR-ALTERACAO-X             PIC X(006).
           05  GER-HR-INCLUSAO-X              PIC X(006).
           05  GER-HR-STAT-ECRV-X             PIC X(006).
           05  GER-ID-CONTR-X                 PIC X(030).
           05  GER-ID-PRESTADORA-X            PIC X(030).
           05  GER-IN-TROCA-MERC-X            PIC X(030).
           05  GER-IND-RENAVE-X               PIC X(030).
           05  GER-LETRA-ANT-X                PIC X(030).
           05  GER-LOC-IMPR-X                 PIC X(030).
           05  GER-MARCA-X                    PIC X(006).
           05  GER-MOTSOL-FICHA-X             PIC X(030).
           05  GER-MUNIC-ANT-X                PIC X(005).
           05  GER-MUNIC-IMOVEL-X             PIC X(005).
           05  GER-MUNIC-PLACA-X              PIC X(010).
           05  GER-NOME-PROPR-X               PIC X(040).
           05  GER-NOMEPROPR-ANT-X            PIC X(040).
           05  GER-NRO-CAMBIO-X               PIC X(030).
           05  GER-NRO-CONTRATO-X             PIC X(010).
           05  GER-NRO-EIXOS-X                PIC X(030).
           05  GER-NRO-ESPELHO-X              PIC X(030).
           05  GER-NRO-FICHA-X                PIC X(030).
           05  GER-NRO-IMOVEL-X               PIC X(030).
           05  GER-NRO-MOTOR-X                PIC X(030).
           05  GER-NRO-NFISCAL-X              PIC X(030).
           05  GER-NUMERO1-ANT-X              PIC X(030).
           05  GER-NUMERO2-ANT-X              PIC X(030).
           05  GER-OPCAO-X                    PIC X(030).
           05  GER-ORG-RG-X                   PIC X(030).
           05  GER-PBT-X                      PIC X(030).
           05  GER-PLA-ANT-MERC-X             PIC X(030).
           05  GER-PLACA-MERC-X               PIC X(010).
           05  GER-PLACA-X                    PIC X(010).
           05  GER-POTENCIA-X                 PIC X(030).
           05  GER-PROCEDENCIA-X              PIC X(030).
           05  GER-PROT-REM-X                 PIC X(030).
           05  GER-RENAVAM-X                  PIC X(011).
           05  GER-RESTR-FINANC-X             PIC X(030).
           05  GER-RET-BIN-X                  PIC X(030).
           05  GER-RET-CONSIST-X              PIC X(030).
           05  GER-RG-X                       PIC X(030).
           05  GER-SEQ-TRANSACAO-X            PIC X(010).
           05  GER-STATUS-ECRV-X              PIC X(020).
           05  GER-STATUS-REG-X               PIC X(020).
           05  GER-TELEFONE-X                 PIC X(010).
           05  GER-TIPO-X                     PIC X(006).
           05  GER-TIPSOL-PLACA-X             PIC X(010).
           05  GER-TP-VEIC-OFIC-X             PIC X(010).
           05  GER-TRANSACAO-X                PIC X(030).
           05  GER-UF-ESP-ANT-X               PIC X(002).
           05  GER-UF-PLACA-ANT-X             PIC X(010).
           05  GER-UF-X                       PIC X(002).
           05  GER-VALOR-NFISCAL-X            PIC X(030).
           05  GER-VISTORIADOR-X              PIC X(030).
           05  GER-ANO                        PIC 9(009).
           05  GER-ANOFABR                    PIC 9(009).
           05  GER-ANOMOD                     PIC 9(009).
           05  GER-ARREND-FIN                 PIC X(030).
           05  GER-AUT-DIGITAL                PIC X(030).
           05  GER-AUT-EMPL                   PIC X(030).
           05  GER-BAIRRO                     PIC X(040).
           05  GER-CAP-CAR                    PIC X(030).
           05  GER-CAP-PAS                    PIC X(030).
           05  GER-CARROCERIA                 PIC X(030).
           05  GER-CATEGORIA                  PIC X(006).
           05  GER-CEP-ENDPROP                PIC X(008).
           05  GER-CHASSI-REM                 PIC X(021).
           05  GER-CHASSI                     PIC X(021).
           05  GER-CHAVEACESS-NF              PIC X(030).
           05  GER-CILINDRADA                 PIC X(030).
           05  GER-CMT                        PIC X(030).
           05  GER-COMBUSTIVEL                PIC X(006).
           05  GER-COMODATO                   PIC X(030).
           05  GER-COMPL                      PIC X(040).
           05  GER-COMTROP5-EXCL              PIC X(030).
           05  GER-CONFERENTE                 PIC X(030).
           05  GER-COR                        PIC X(030).
           05  GER-CPF-CGC                    PIC X(014).
           05  GER-CPF-USUSTAT                PIC X(011).
           05  GER-DATA-VENDA                 PIC X(010).
           05  GER-DESP-SSP                   PIC X(030).
           05  GER-DIGITADOR                  PIC X(030).
           05  GER-DT-ALTERACAO               PIC 9(009).
           05  GER-DT-CONFERENTE              PIC 9(009).
           05  GER-DT-DIGITADOR               PIC 9(009).
           05  GER-DT-EMIS-NF                 PIC 9(009).
           05  GER-DT-INCLUSAO                PIC 9(009).
           05  GER-DT-REC-DOCTS               PIC 9(009).
           05  GER-DT-STAT-ECRV               PIC 9(009).
           05  GER-DT-VIG-CONTR               PIC 9(009).
           05  GER-DT-VIST                    PIC 9(009).
           05  GER-ENDERECO                   PIC X(040).
           05  GER-ESPECIE                    PIC X(006).
           05  GER-ESPELHO-ANT                PIC X(030).
           05  GER-FILLER1                    PIC X(020).
           05  GER-FILLER2                    PIC X(020).
           05  GER-FILLER3                    PIC X(020).
           05  GER-FILLER4                    PIC X(020).
           05  GER-FILLER5                    PIC X(020).
           05  GER-FINANC                     PIC X(030).
           05  GER-HR-ALTERACAO               PIC 9(009).
           05  GER-HR-INCLUSAO                PIC 9(009).
           05  GER-HR-STAT-ECRV               PIC 9(009).
           05  GER-ID-CONTR                   PIC X(030).
           05  GER-ID-PRESTADORA              PIC X(030).
           05  GER-IN-TROCA-MERC              PIC X(030).
           05  GER-IND-RENAVE                 PIC X(030).
           05  GER-LETRA-ANT                  PIC X(030).
           05  GER-LOC-IMPR                   PIC X(030).
           05  GER-MARCA                      PIC X(006).
           05  GER-MOTSOL-FICHA               PIC X(030).
           05  GER-MUNIC-ANT                  PIC X(005).
           05  GER-MUNIC-IMOVEL               PIC X(005).
           05  GER-MUNIC-PLACA                PIC X(010).
           05  GER-NOME-PROPR                 PIC X(040).
           05  GER-NOMEPROPR-ANT              PIC X(040).
           05  GER-NRO-CAMBIO                 PIC X(030).
           05  GER-NRO-CONTRATO               PIC X(010).
           05  GER-NRO-EIXOS                  PIC X(030).
           05  GER-NRO-ESPELHO                PIC X(030).
           05  GER-NRO-FICHA                  PIC X(030).
           05  GER-NRO-IMOVEL                 PIC X(030).
           05  GER-NRO-MOTOR                  PIC X(030).
           05  GER-NRO-NFISCAL                PIC X(030).
           05  GER-NUMERO1-ANT                PIC X(030).
           05  GER-NUMERO2-ANT                PIC X(030).
           05  GER-OPCAO                      PIC X(030).
           05  GER-ORG-RG                     PIC X(030).
           05  GER-PBT                        PIC X(030).
           05  GER-PLA-ANT-MERC               PIC X(030).
           05  GER-PLACA-MERC                 PIC X(010).
           05  GER-PLACA                      PIC X(010).
           05  GER-POTENCIA                   PIC X(030).
           05  GER-PROCEDENCIA                PIC X(030).
           05  GER-PROT-REM                   PIC X(030).
           05  GER-RENAVAM                    PIC X(011).
           05  GER-RESTR-FINANC               PIC X(030).
           05  GER-RET-BIN                    PIC X(030).
           05  GER-RET-CONSIST                PIC X(030).
           05  GER-RG                         PIC X(030).
           05  GER-SEQ-TRANSACAO              PIC 9(009).
           05  GER-STATUS-ECRV                PIC X(020).
           05  GER-STATUS-REG                 PIC X(020).
           05  GER-TELEFONE                   PIC X(010).
           05  GER-TIPO                       PIC X(006).
           05  GER-TIPSOL-PLACA               PIC X(010).
           05  GER-TP-VEIC-OFIC               PIC X(010).
           05  GER-TRANSACAO                  PIC X(030).
           05  GER-UF-ESP-ANT                 PIC X(002).
           05  GER-UF-PLACA-ANT               PIC X(010).
           05  GER-UF                         PIC X(002).
           05  GER-VALOR-NFISCAL              PIC X(030).
           05  GER-VISTORIADOR                PIC X(030).
