      * WSD copybook for RECUPERADODS (auto-generated)
       01  RECUPERADODS.
           05  RECUPERADODS-ROWID             PIC X(018).
           05  REC-ANO-BOQ-X                  PIC X(004).
           05  REC-ANO-BOR-X                  PIC X(004).
           05  REC-ANOFABR-X                  PIC X(004).
           05  REC-ANOMOD-X                   PIC X(004).
           05  REC-BAIRRO-X                   PIC X(040).
           05  REC-BO-QUEIXA-X                PIC X(012).
           05  REC-BO-RECUP-X                 PIC X(012).
           05  REC-BOSPJQ-ANO-X               PIC X(004).
           05  REC-BOSPJQ-COD-X               PIC X(012).
           05  REC-BOSPJR-ANO-X               PIC X(004).
           05  REC-BOSPJR-COD-X               PIC X(012).
           05  REC-CEP-X                      PIC X(008).
           05  REC-CHASSIS-X                  PIC X(021).
           05  REC-COMPL-X                    PIC X(040).
           05  REC-COR-X                      PIC X(030).
           05  REC-DDD-X                      PIC X(010).
           05  REC-DELEG-QUEIXA-X             PIC X(030).
           05  REC-DELEG-RECUP-X              PIC X(030).
           05  REC-DOC-VITIMA-X               PIC X(030).
           05  REC-DT-CADQUE-X                PIC X(010).
           05  REC-DT-CADRECUP-X              PIC X(010).
           05  REC-DT-QUEIXA-X                PIC X(010).
           05  REC-DT-RECUP-X                 PIC X(010).
           05  REC-FILLER1-X                  PIC X(020).
           05  REC-FILLER102-X                PIC X(020).
           05  REC-FILLER11-X                 PIC X(020).
           05  REC-FILLER2-X                  PIC X(020).
           05  REC-FILLER3-X                  PIC X(020).
           05  REC-FILLER4-X                  PIC X(020).
           05  REC-FILLER5-X                  PIC X(020).
           05  REC-FILLER6-X                  PIC X(020).
           05  REC-FILLER7-X                  PIC X(020).
           05  REC-FILLER8-X                  PIC X(020).
           05  REC-FILLER9-X                  PIC X(020).
           05  REC-HR-CADQUE-X                PIC X(006).
           05  REC-HR-CADRECUP-X              PIC X(006).
           05  REC-HR-QUEIXA-X                PIC X(006).
           05  REC-HR-RECUP-X                 PIC X(006).
           05  REC-IPANO-X                    PIC X(030).
           05  REC-IPNUM-X                    PIC X(030).
           05  REC-LOGRADOURO-X               PIC X(040).
           05  REC-MARCA-X                    PIC X(006).
           05  REC-MUNIC-END-X                PIC X(005).
           05  REC-MUNIC-QUEIXA-X             PIC X(005).
           05  REC-MUNIC-RECUP-X              PIC X(005).
           05  REC-MUNICIPIO-X                PIC X(005).
           05  REC-NOME-VITIMA-X              PIC X(040).
           05  REC-NUMERO-END-X               PIC X(030).
           05  REC-PLACA-X                    PIC X(010).
           05  REC-PLACAX-X                   PIC X(010).
           05  REC-RAMAL-X                    PIC X(010).
           05  REC-RENAVAM-X                  PIC X(011).
           05  REC-TELEFONE-X                 PIC X(010).
           05  REC-TIPO-DECL-X                PIC X(006).
           05  REC-TIPO-DOC-X                 PIC X(006).
           05  REC-TIPO-X                     PIC X(006).
           05  REC-UF-BOQ-X                   PIC X(002).
           05  REC-UF-BOR-X                   PIC X(002).
           05  REC-UF-JURISD-X                PIC X(002).
           05  REC-USU-QUEIXA-X               PIC X(008).
           05  REC-USU-RECUP-X                PIC X(008).
           05  REC-ANO-BOQ                    PIC 9(009).
           05  REC-ANO-BOR                    PIC 9(009).
           05  REC-ANOFABR                    PIC 9(009).
           05  REC-ANOMOD                     PIC 9(009).
           05  REC-BAIRRO                     PIC X(040).
           05  REC-BO-QUEIXA                  PIC X(012).
           05  REC-BO-RECUP                   PIC X(012).
           05  REC-BOSPJQ-ANO                 PIC 9(009).
           05  REC-BOSPJQ-COD                 PIC X(012).
           05  REC-BOSPJR-ANO                 PIC 9(009).
           05  REC-BOSPJR-COD                 PIC X(012).
           05  REC-CEP                        PIC X(008).
           05  REC-CHASSIS                    PIC X(021).
           05  REC-COMPL                      PIC X(040).
           05  REC-COR                        PIC X(030).
           05  REC-DDD                        PIC X(010).
           05  REC-DELEG-QUEIXA               PIC X(030).
           05  REC-DELEG-RECUP                PIC X(030).
           05  REC-DOC-VITIMA                 PIC X(030).
           05  REC-DT-CADQUE                  PIC 9(009).
           05  REC-DT-CADRECUP                PIC 9(009).
           05  REC-DT-QUEIXA                  PIC 9(009).
           05  REC-DT-RECUP                   PIC 9(009).
           05  REC-FILLER1                    PIC X(020).
           05  REC-FILLER102                  PIC X(020).
           05  REC-FILLER11                   PIC X(020).
           05  REC-FILLER2                    PIC X(020).
           05  REC-FILLER3                    PIC X(020).
           05  REC-FILLER4                    PIC X(020).
           05  REC-FILLER5                    PIC X(020).
           05  REC-FILLER6                    PIC X(020).
           05  REC-FILLER7                    PIC X(020).
           05  REC-FILLER8                    PIC X(020).
           05  REC-FILLER9                    PIC X(020).
           05  REC-HR-CADQUE                  PIC 9(009).
           05  REC-HR-CADRECUP                PIC 9(009).
           05  REC-HR-QUEIXA                  PIC 9(009).
           05  REC-HR-RECUP                   PIC 9(009).
           05  REC-IPANO                      PIC X(030).
           05  REC-IPNUM                      PIC X(030).
           05  REC-LOGRADOURO                 PIC X(040).
           05  REC-MARCA                      PIC X(006).
           05  REC-MUNIC-END                  PIC X(005).
           05  REC-MUNIC-QUEIXA               PIC X(005).
           05  REC-MUNIC-RECUP                PIC X(005).
           05  REC-MUNICIPIO                  PIC 9(009).
           05  REC-NOME-VITIMA                PIC X(040).
           05  REC-NUMERO-END                 PIC X(030).
           05  REC-PLACA                      PIC X(010).
           05  REC-PLACAX                     PIC X(010).
           05  REC-RAMAL                      PIC X(010).
           05  REC-RENAVAM                    PIC X(011).
           05  REC-TELEFONE                   PIC X(010).
           05  REC-TIPO-DECL                  PIC X(006).
           05  REC-TIPO-DOC                   PIC X(006).
           05  REC-TIPO                       PIC X(006).
           05  REC-UF-BOQ                     PIC X(002).
           05  REC-UF-BOR                     PIC X(002).
           05  REC-UF-JURISD                  PIC X(002).
           05  REC-USU-QUEIXA                 PIC X(008).
           05  REC-USU-RECUP                  PIC X(008).
