      * WSD copybook for GEVINATIVODS (auto-generated)
       01  GEVINATIVODS.
           05  GEVINATIVODS-ROWID             PIC X(018).
           05  GEI-ANO-X                      PIC X(004).
           05  GEI-ANOFABR-X                  PIC X(004).
           05  GEI-ANOMOD-X                   PIC X(004).
           05  GEI-ARREND-FIN-X               PIC X(030).
           05  GEI-AUT-DIGITAL-X              PIC X(030).
           05  GEI-AUT-EMPL-X                 PIC X(030).
           05  GEI-BAIRRO-X                   PIC X(040).
           05  GEI-CAP-CAR-X                  PIC X(030).
           05  GEI-CAP-PAS-X                  PIC X(030).
           05  GEI-CARROCERIA-X               PIC X(030).
           05  GEI-CATEGORIA-X                PIC X(006).
           05  GEI-CEP-ENDPROP-X              PIC X(008).
           05  GEI-CHASSI-REM-X               PIC X(021).
           05  GEI-CHASSI-X                   PIC X(021).
           05  GEI-CHAVEACESS-NF-X            PIC X(030).
           05  GEI-CILINDRADA-X               PIC X(030).
           05  GEI-CMT-X                      PIC X(030).
           05  GEI-COMBUSTIVEL-X              PIC X(006).
           05  GEI-COMODATO-X                 PIC X(030).
           05  GEI-COMPL-X                    PIC X(040).
           05  GEI-COMTROP5-EXCL-X            PIC X(030).
           05  GEI-CONFERENTE-X               PIC X(030).
           05  GEI-COR-X                      PIC X(030).
           05  GEI-CPF-CGC-X                  PIC X(014).
           05  GEI-CPF-USUSTAT-X              PIC X(011).
           05  GEI-DATA-VENDA-X               PIC X(010).
           05  GEI-DESP-SSP-X                 PIC X(030).
           05  GEI-DIGITADOR-X                PIC X(030).
           05  GEI-DT-ALTERACAO-X             PIC X(010).
           05  GEI-DT-CONFERENTE-X            PIC X(010).
           05  GEI-DT-DIGITADOR-X             PIC X(010).
           05  GEI-DT-EMIS-DOCTO-X            PIC X(010).
           05  GEI-DT-EMIS-NF-X               PIC X(010).
           05  GEI-DT-ENT-DOCTO-X             PIC X(010).
           05  GEI-DT-INATIVO-X               PIC X(010).
           05  GEI-DT-INCLUSAO-X              PIC X(010).
           05  GEI-DT-REC-DOCTS-X             PIC X(010).
           05  GEI-DT-STAT-ECRV-X             PIC X(010).
           05  GEI-DT-VIG-CONTR-X             PIC X(010).
           05  GEI-DT-VIST-X                  PIC X(010).
           05  GEI-ENDERECO-X                 PIC X(040).
           05  GEI-ESPECIE-X                  PIC X(006).
           05  GEI-ESPELHO-ANT-X              PIC X(030).
           05  GEI-FILLER1-X                  PIC X(020).
           05  GEI-FILLER2-X                  PIC X(020).
           05  GEI-FILLER3-X                  PIC X(020).
           05  GEI-FILLER4-X                  PIC X(020).
           05  GEI-FILLER5-X                  PIC X(020).
           05  GEI-FINANC-X                   PIC X(030).
           05  GEI-HR-ALTERACAO-X             PIC X(006).
           05  GEI-HR-EMIS-DOCTO-X            PIC X(006).
           05  GEI-HR-ENT-DOCTO-X             PIC X(006).
           05  GEI-HR-INATIVO-X               PIC X(006).
           05  GEI-HR-INCLUSAO-X              PIC X(006).
           05  GEI-HR-STAT-ECRV-X             PIC X(006).
           05  GEI-ID-CONTR-X                 PIC X(030).
           05  GEI-ID-PRESTADORA-X            PIC X(030).
           05  GEI-IN-TROCA-MERC-X            PIC X(030).
           05  GEI-IND-RENAVE-X               PIC X(030).
           05  GEI-LETRA-ANT-X                PIC X(030).
           05  GEI-LOC-IMPR-X                 PIC X(030).
           05  GEI-MARCA-X                    PIC X(006).
           05  GEI-MOTSOL-FICHA-X             PIC X(030).
           05  GEI-MUNIC-ANT-X                PIC X(005).
           05  GEI-MUNIC-IMOVEL-X             PIC X(005).
           05  GEI-MUNIC-PLACA-X              PIC X(010).
           05  GEI-NOME-PROPR-X               PIC X(040).
           05  GEI-NOMEPROPR-ANT-X            PIC X(040).
           05  GEI-NRO-CAMBIO-X               PIC X(030).
           05  GEI-NRO-CONTRATO-X             PIC X(010).
           05  GEI-NRO-EIXOS-X                PIC X(030).
           05  GEI-NRO-ESPELHO-X              PIC X(030).
           05  GEI-NRO-FICHA-X                PIC X(030).
           05  GEI-NRO-FISCAL-X               PIC X(030).
           05  GEI-NRO-IMOVEL-X               PIC X(030).
           05  GEI-NRO-MOTOR-X                PIC X(030).
           05  GEI-NUMERO1-ANT-X              PIC X(030).
           05  GEI-NUMERO2-ANT-X              PIC X(030).
           05  GEI-OPCAO-X                    PIC X(030).
           05  GEI-ORG-RG-X                   PIC X(030).
           05  GEI-PBT-X                      PIC X(030).
           05  GEI-PLA-ANT-MERC-X             PIC X(030).
           05  GEI-PLACA-MERC-X               PIC X(010).
           05  GEI-PLACA-X                    PIC X(010).
           05  GEI-POTENCIA-X                 PIC X(030).
           05  GEI-PROCEDENCIA-X              PIC X(030).
           05  GEI-PROT-REM-X                 PIC X(030).
           05  GEI-RENAVAM-X                  PIC X(011).
           05  GEI-RESTR-FINANC-X             PIC X(030).
           05  GEI-RET-BIN-X                  PIC X(030).
           05  GEI-RET-CONSIST-X              PIC X(030).
           05  GEI-RG-X                       PIC X(030).
           05  GEI-SEQ-TRANSACAO-X            PIC X(010).
           05  GEI-STATUS-ECRV-X              PIC X(020).
           05  GEI-STATUS-REG-X               PIC X(020).
           05  GEI-TELEFONE-X                 PIC X(010).
           05  GEI-TIPO-X                     PIC X(006).
           05  GEI-TIPSOL-PLACA-X             PIC X(010).
           05  GEI-TP-VEIC-OFIC-X             PIC X(010).
           05  GEI-TRANSACAO-X                PIC X(030).
           05  GEI-UF-ESP-ANT-X               PIC X(002).
           05  GEI-UF-PLACA-ANT-X             PIC X(010).
           05  GEI-UF-X                       PIC X(002).
           05  GEI-USUARIO-X                  PIC X(008).
           05  GEI-VALOR-NFISCAL-X            PIC X(030).
           05  GEI-VISTORIADOR-X              PIC X(030).
           05  GEI-ANO                        PIC 9(009).
           05  GEI-ANOFABR                    PIC 9(009).
           05  GEI-ANOMOD                     PIC 9(009).
           05  GEI-ARREND-FIN                 PIC X(030).
           05  GEI-AUT-DIGITAL                PIC X(030).
           05  GEI-AUT-EMPL                   PIC X(030).
           05  GEI-BAIRRO                     PIC X(040).
           05  GEI-CAP-CAR                    PIC X(030).
           05  GEI-CAP-PAS                    PIC X(030).
           05  GEI-CARROCERIA                 PIC X(030).
           05  GEI-CATEGORIA                  PIC X(006).
           05  GEI-CEP-ENDPROP                PIC X(008).
           05  GEI-CHASSI-REM                 PIC X(021).
           05  GEI-CHASSI                     PIC X(021).
           05  GEI-CHAVEACESS-NF              PIC X(030).
           05  GEI-CILINDRADA                 PIC X(030).
           05  GEI-CMT                        PIC X(030).
           05  GEI-COMBUSTIVEL                PIC X(006).
           05  GEI-COMODATO                   PIC X(030).
           05  GEI-COMPL                      PIC X(040).
           05  GEI-COMTROP5-EXCL              PIC X(030).
           05  GEI-CONFERENTE                 PIC X(030).
           05  GEI-COR                        PIC X(030).
           05  GEI-CPF-CGC                    PIC X(014).
           05  GEI-CPF-USUSTAT                PIC X(011).
           05  GEI-DATA-VENDA                 PIC X(010).
           05  GEI-DESP-SSP                   PIC X(030).
           05  GEI-DIGITADOR                  PIC X(030).
           05  GEI-DT-ALTERACAO               PIC 9(009).
           05  GEI-DT-CONFERENTE              PIC 9(009).
           05  GEI-DT-DIGITADOR               PIC 9(009).
           05  GEI-DT-EMIS-DOCTO              PIC 9(009).
           05  GEI-DT-EMIS-NF                 PIC 9(009).
           05  GEI-DT-ENT-DOCTO               PIC 9(009).
           05  GEI-DT-INATIVO                 PIC 9(009).
           05  GEI-DT-INCLUSAO                PIC 9(009).
           05  GEI-DT-REC-DOCTS               PIC 9(009).
           05  GEI-DT-STAT-ECRV               PIC 9(009).
           05  GEI-DT-VIG-CONTR               PIC 9(009).
           05  GEI-DT-VIST                    PIC 9(009).
           05  GEI-ENDERECO                   PIC X(040).
           05  GEI-ESPECIE                    PIC X(006).
           05  GEI-ESPELHO-ANT                PIC X(030).
           05  GEI-FILLER1                    PIC X(020).
           05  GEI-FILLER2                    PIC X(020).
           05  GEI-FILLER3                    PIC X(020).
           05  GEI-FILLER4                    PIC X(020).
           05  GEI-FILLER5                    PIC X(020).
           05  GEI-FINANC                     PIC X(030).
           05  GEI-HR-ALTERACAO               PIC 9(009).
           05  GEI-HR-EMIS-DOCTO              PIC 9(009).
           05  GEI-HR-ENT-DOCTO               PIC 9(009).
           05  GEI-HR-INATIVO                 PIC 9(009).
           05  GEI-HR-INCLUSAO                PIC 9(009).
           05  GEI-HR-STAT-ECRV               PIC 9(009).
           05  GEI-ID-CONTR                   PIC X(030).
           05  GEI-ID-PRESTADORA              PIC X(030).
           05  GEI-IN-TROCA-MERC              PIC X(030).
           05  GEI-IND-RENAVE                 PIC X(030).
           05  GEI-LETRA-ANT                  PIC X(030).
           05  GEI-LOC-IMPR                   PIC X(030).
           05  GEI-MARCA                      PIC X(006).
           05  GEI-MOTSOL-FICHA               PIC X(030).
           05  GEI-MUNIC-ANT                  PIC X(005).
           05  GEI-MUNIC-IMOVEL               PIC X(005).
           05  GEI-MUNIC-PLACA                PIC X(010).
           05  GEI-NOME-PROPR                 PIC X(040).
           05  GEI-NOMEPROPR-ANT              PIC X(040).
           05  GEI-NRO-CAMBIO                 PIC X(030).
           05  GEI-NRO-CONTRATO               PIC X(010).
           05  GEI-NRO-EIXOS                  PIC X(030).
           05  GEI-NRO-ESPELHO                PIC X(030).
           05  GEI-NRO-FICHA                  PIC X(030).
           05  GEI-NRO-FISCAL                 PIC X(030).
           05  GEI-NRO-IMOVEL                 PIC X(030).
           05  GEI-NRO-MOTOR                  PIC X(030).
           05  GEI-NUMERO1-ANT                PIC X(030).
           05  GEI-NUMERO2-ANT                PIC X(030).
           05  GEI-OPCAO                      PIC X(030).
           05  GEI-ORG-RG                     PIC X(030).
           05  GEI-PBT                        PIC X(030).
           05  GEI-PLA-ANT-MERC               PIC X(030).
           05  GEI-PLACA-MERC                 PIC X(010).
           05  GEI-PLACA                      PIC X(010).
           05  GEI-POTENCIA                   PIC X(030).
           05  GEI-PROCEDENCIA                PIC X(030).
           05  GEI-PROT-REM                   PIC X(030).
           05  GEI-RENAVAM                    PIC X(011).
           05  GEI-RESTR-FINANC               PIC X(030).
           05  GEI-RET-BIN                    PIC X(030).
           05  GEI-RET-CONSIST                PIC X(030).
           05  GEI-RG                         PIC X(030).
           05  GEI-SEQ-TRANSACAO              PIC 9(009).
           05  GEI-STATUS-ECRV                PIC X(020).
           05  GEI-STATUS-REG                 PIC X(020).
           05  GEI-TELEFONE                   PIC X(010).
           05  GEI-TIPO                       PIC X(006).
           05  GEI-TIPSOL-PLACA               PIC X(010).
           05  GEI-TP-VEIC-OFIC               PIC X(010).
           05  GEI-TRANSACAO                  PIC X(030).
           05  GEI-UF-ESP-ANT                 PIC X(002).
           05  GEI-UF-PLACA-ANT               PIC X(010).
           05  GEI-UF                         PIC X(002).
           05  GEI-USUARIO                    PIC X(008).
           05  GEI-VALOR-NFISCAL              PIC X(030).
           05  GEI-VISTORIADOR                PIC X(030).
