      * WSD copybook for GEVLACRACAODS (auto-generated)
       01  GEVLACRACAODS.
           05  GEVLACRACAODS-ROWID            PIC X(018).
           05  GEL-BANCO-X                    PIC X(030).
           05  GEL-CPF-CNPJ-X                 PIC X(011).
           05  GEL-DESP-SSP-X                 PIC X(030).
           05  GEL-DT-ATUAL-X                 PIC X(010).
           05  GEL-DT-EMISSAO-X               PIC X(010).
           05  GEL-DT-INCLUSAO-X              PIC X(010).
           05  GEL-DT-LACRACAO-X              PIC X(010).
           05  GEL-FORNECEDOR-X               PIC X(030).
           05  GEL-HR-ATUAL-X                 PIC X(006).
           05  GEL-HR-EMISSAO-X               PIC X(006).
           05  GEL-HR-INCLUSAO-X              PIC X(006).
           05  GEL-HR-LACRACAO-X              PIC X(006).
           05  GEL-MUNICIPIO-X                PIC X(005).
           05  GEL-NRO-LACRE-X                PIC X(030).
           05  GEL-OPCAO-X                    PIC X(030).
           05  GEL-PLACA-MERC-X               PIC X(010).
           05  GEL-PLACA-X                    PIC X(010).
           05  GEL-PRESTADORA-X               PIC X(030).
           05  GEL-RENAVAM-X                  PIC X(011).
           05  GEL-TIPO-DOC-X                 PIC X(006).
           05  GEL-VALOR-X                    PIC X(030).
           05  GEL-BANCO                      PIC X(030).
           05  GEL-CPF-CNPJ                   PIC X(011).
           05  GEL-DESP-SSP                   PIC X(030).
           05  GEL-DT-ATUAL                   PIC 9(009).
           05  GEL-DT-EMISSAO                 PIC 9(009).
           05  GEL-DT-INCLUSAO                PIC 9(009).
           05  GEL-DT-LACRACAO                PIC 9(009).
           05  GEL-FORNECEDOR                 PIC X(030).
           05  GEL-HR-ATUAL                   PIC 9(009).
           05  GEL-HR-EMISSAO                 PIC 9(009).
           05  GEL-HR-INCLUSAO                PIC 9(009).
           05  GEL-HR-LACRACAO                PIC 9(009).
           05  GEL-MUNICIPIO                  PIC 9(009).
           05  GEL-NRO-LACRE                  PIC X(030).
           05  GEL-OPCAO                      PIC X(030).
           05  GEL-PLACA-MERC                 PIC X(010).
           05  GEL-PLACA                      PIC X(010).
           05  GEL-PRESTADORA                 PIC X(030).
           05  GEL-RENAVAM                    PIC X(011).
           05  GEL-TIPO-DOC                   PIC X(006).
           05  GEL-VALOR                      PIC X(030).
