      * WSD copybook for DESBLOQUEIODS (auto-generated)
       01  DESBLOQUEIODS.
           05  DESBLOQUEIODS-ROWID            PIC X(018).
           05  DES-ANO-OFIC-X                 PIC X(004).
           05  DES-ANO-PROCESSO-X             PIC X(004).
           05  DES-ANO-PROTOC-X               PIC X(004).
           05  DES-ANOFIC-DESB-X              PIC X(004).
           05  DES-ANPROC-DESB-X              PIC X(030).
           05  DES-ANPROT-DESB-X              PIC X(030).
           05  DES-AUTOR-DESB-X               PIC X(030).
           05  DES-AUTORIDADE-X               PIC X(030).
           05  DES-CD-ORG-BLOQ-X              PIC X(006).
           05  DES-CHASSIS-X                  PIC X(021).
           05  DES-CSV-ANO-X                  PIC X(004).
           05  DES-CSV-X                      PIC X(030).
           05  DES-DT-DESB-X                  PIC X(010).
           05  DES-DT-INCLUSAO-X              PIC X(010).
           05  DES-DT-VALID-AUT-X             PIC X(010).
           05  DES-FILLER-X                   PIC X(020).
           05  DES-FILLER1-X                  PIC X(020).
           05  DES-FILLER2-X                  PIC X(020).
           05  DES-FILLER3-X                  PIC X(020).
           05  DES-HR-DESB-X                  PIC X(006).
           05  DES-HR-INCLUSAO-X              PIC X(006).
           05  DES-MUNIC-LEILAO-X             PIC X(005).
           05  DES-MUNICIPIO-X                PIC X(005).
           05  DES-NUM-OFIC-X                 PIC X(010).
           05  DES-NUM-PROCESSO-X             PIC X(010).
           05  DES-NUM-PROTOC-X               PIC X(010).
           05  DES-NUOFIC-DESB-X              PIC X(010).
           05  DES-NUPROC-DESB-X              PIC X(030).
           05  DES-NUPROT-DESB-X              PIC X(030).
           05  DES-PLACA-MERC-X               PIC X(010).
           05  DES-PLACA-X                    PIC X(010).
           05  DES-TIP-BLOQ-X                 PIC X(006).
           05  DES-USU-DESB-X                 PIC X(008).
           05  DES-USUARIO-X                  PIC X(008).
           05  DES-ANO-OFIC                   PIC 9(009).
           05  DES-ANO-PROCESSO               PIC 9(009).
           05  DES-ANO-PROTOC                 PIC 9(009).
           05  DES-ANOFIC-DESB                PIC 9(009).
           05  DES-ANPROC-DESB                PIC X(030).
           05  DES-ANPROT-DESB                PIC X(030).
           05  DES-AUTOR-DESB                 PIC X(030).
           05  DES-AUTORIDADE                 PIC X(030).
           05  DES-CD-ORG-BLOQ                PIC X(006).
           05  DES-CHASSIS                    PIC X(021).
           05  DES-CSV-ANO                    PIC 9(009).
           05  DES-CSV                        PIC X(030).
           05  DES-DT-DESB                    PIC 9(009).
           05  DES-DT-INCLUSAO                PIC 9(009).
           05  DES-DT-VALID-AUT               PIC 9(009).
           05  DES-FILLER                     PIC X(020).
           05  DES-FILLER1                    PIC X(020).
           05  DES-FILLER2                    PIC X(020).
           05  DES-FILLER3                    PIC X(020).
           05  DES-HR-DESB                    PIC 9(009).
           05  DES-HR-INCLUSAO                PIC 9(009).
           05  DES-MUNIC-LEILAO               PIC X(005).
           05  DES-MUNICIPIO                  PIC 9(009).
           05  DES-NUM-OFIC                   PIC 9(009).
           05  DES-NUM-PROCESSO               PIC 9(009).
           05  DES-NUM-PROTOC                 PIC 9(009).
           05  DES-NUOFIC-DESB                PIC X(010).
           05  DES-NUPROC-DESB                PIC X(030).
           05  DES-NUPROT-DESB                PIC X(030).
           05  DES-PLACA-MERC                 PIC X(010).
           05  DES-PLACA                      PIC X(010).
           05  DES-TIP-BLOQ                   PIC X(006).
           05  DES-USU-DESB                   PIC X(008).
           05  DES-USUARIO                    PIC X(008).
