      * WSD copybook for CSVCERTDS (auto-generated)
       01  CSVCERTDS.
           05  CSVCERTDS-ROWID                PIC X(018).
           05  CSV-ANO-CERTIF-X               PIC X(004).
           05  CSV-CHASSIS-X                  PIC X(021).
           05  CSV-CNPJ-CERTIF-X              PIC X(014).
           05  CSV-CNPJ-UGC-X                 PIC X(014).
           05  CSV-DT-EMI-CERTIF-X            PIC X(010).
           05  CSV-DT-INCLUSAO-X              PIC X(010).
           05  CSV-HR-INCLUSAO-X              PIC X(006).
           05  CSV-MARCA-X                    PIC X(006).
           05  CSV-MUNIC-PLACA-X              PIC X(010).
           05  CSV-NUM-CERTIF-X               PIC X(010).
           05  CSV-PLACA-MERC-X               PIC X(010).
           05  CSV-PLACA-X                    PIC X(010).
           05  CSV-RENAVAM-X                  PIC X(011).
           05  CSV-TIPO-CERTIF-X              PIC X(006).
           05  CSV-TIPO-X                     PIC X(006).
           05  CSV-UF-CERTIF-X                PIC X(002).
           05  CSV-UF-PLACA-X                 PIC X(010).
           05  CSV-USU-INCLUSAO-X             PIC X(008).
           05  CSV-ANO-CERTIF                 PIC 9(009).
           05  CSV-CHASSIS                    PIC X(021).
           05  CSV-CNPJ-CERTIF                PIC X(014).
           05  CSV-CNPJ-UGC                   PIC X(014).
           05  CSV-DT-EMI-CERTIF              PIC 9(009).
           05  CSV-DT-INCLUSAO                PIC 9(009).
           05  CSV-HR-INCLUSAO                PIC 9(009).
           05  CSV-MARCA                      PIC X(006).
           05  CSV-MUNIC-PLACA                PIC X(010).
           05  CSV-NUM-CERTIF                 PIC 9(009).
           05  CSV-PLACA-MERC                 PIC X(010).
           05  CSV-PLACA                      PIC X(010).
           05  CSV-RENAVAM                    PIC X(011).
           05  CSV-TIPO-CERTIF                PIC X(006).
           05  CSV-TIPO                       PIC X(006).
           05  CSV-UF-CERTIF                  PIC X(002).
           05  CSV-UF-PLACA                   PIC X(010).
           05  CSV-USU-INCLUSAO               PIC X(008).
