      * WSD copybook for PRODDUTDS (auto-generated)
       01  PRODDUTDS.
           05  PRODDUTDS-ROWID                PIC X(018).
           05  DUT-ANO-BO-X                   PIC X(004).
           05  DUT-ANO-OFIC-X                 PIC X(004).
           05  DUT-ANO-PROT-X                 PIC X(004).
           05  DUT-COMUNICADO-X               PIC X(005).
           05  DUT-DATA-X                     PIC X(010).
           05  DUT-DATAPUBL-X                 PIC X(010).
           05  DUT-DELEG-BO-X                 PIC X(030).
           05  DUT-DOC-X                      PIC X(030).
           05  DUT-DT-BO-X                    PIC X(010).
           05  DUT-DT-OCOR-X                  PIC X(010).
           05  DUT-DT-OFIC-X                  PIC X(010).
           05  DUT-EST-X                      PIC X(030).
           05  DUT-HR-INCLUSAO-X              PIC X(006).
           05  DUT-LOCAL-OCOR-X               PIC X(030).
           05  DUT-MUNICIPIO-X                PIC X(005).
           05  DUT-NATUREZA-X                 PIC X(030).
           05  DUT-NRO-BO-X                   PIC X(030).
           05  DUT-NUM-FIM-X                  PIC X(010).
           05  DUT-NUM-INI-X                  PIC X(010).
           05  DUT-NUM-OFIC-X                 PIC X(010).
           05  DUT-NUM-PROT-X                 PIC X(010).
           05  DUT-NUM-X                      PIC X(030).
           05  DUT-ORIGEM-OFIC-X              PIC X(010).
           05  DUT-SIT-X                      PIC X(030).
           05  DUT-TIPO-X                     PIC X(006).
           05  DUT-USU-INCL-X                 PIC X(008).
           05  DUT-ANO-BO                     PIC 9(009).
           05  DUT-ANO-OFIC                   PIC 9(009).
           05  DUT-ANO-PROT                   PIC 9(009).
           05  DUT-COMUNICADO                 PIC X(005).
           05  DUT-DATA                       PIC X(010).
           05  DUT-DATAPUBL                   PIC X(010).
           05  DUT-DELEG-BO                   PIC X(030).
           05  DUT-DOC                        PIC X(030).
           05  DUT-DT-BO                      PIC 9(009).
           05  DUT-DT-OCOR                    PIC 9(009).
           05  DUT-DT-OFIC                    PIC 9(009).
           05  DUT-EST                        PIC X(030).
           05  DUT-HR-INCLUSAO                PIC 9(009).
           05  DUT-LOCAL-OCOR                 PIC X(030).
           05  DUT-MUNICIPIO                  PIC 9(009).
           05  DUT-NATUREZA                   PIC X(030).
           05  DUT-NRO-BO                     PIC X(030).
           05  DUT-NUM-FIM                    PIC 9(009).
           05  DUT-NUM-INI                    PIC 9(009).
           05  DUT-NUM-OFIC                   PIC 9(009).
           05  DUT-NUM-PROT                   PIC 9(009).
           05  DUT-NUM                        PIC X(030).
           05  DUT-ORIGEM-OFIC                PIC X(010).
           05  DUT-SIT                        PIC X(030).
           05  DUT-TIPO                       PIC X(006).
           05  DUT-USU-INCL                   PIC X(008).
