      * WSD copybook for GRAVAMESDS (auto-generated)
       01  GRAVAMESDS.
           05  GRAVAMESDS-ROWID               PIC X(018).
           05  GRA-ANO-TRANSACAO-X            PIC X(004).
           05  GRA-ANOFABR-X                  PIC X(004).
           05  GRA-ANOMOD-X                   PIC X(004).
           05  GRA-CD-AGENTE-X                PIC X(006).
           05  GRA-CGC-AGENTE-X               PIC X(014).
           05  GRA-CHASSI-REM-X               PIC X(021).
           05  GRA-CHASSI-X                   PIC X(021).
           05  GRA-CPF-CGC-ANTIG-X            PIC X(014).
           05  GRA-CPF-CGC-FINAN-X            PIC X(014).
           05  GRA-CPF-CGC-NOVO-X             PIC X(014).
           05  GRA-DIA-JULIANO-X              PIC X(030).
           05  GRA-DT-CONTR-VIG-X             PIC X(010).
           05  GRA-DT-EMISSAO-X               PIC X(010).
           05  GRA-DT-INCLUSAO-X              PIC X(010).
           05  GRA-FILLER1-X                  PIC X(020).
           05  GRA-FILLER2-X                  PIC X(020).
           05  GRA-HR-EMISSAO-X               PIC X(006).
           05  GRA-HR-INCLUSAO-X              PIC X(006).
           05  GRA-NOME-AGENTE-X              PIC X(040).
           05  GRA-NOME-FIN-NOVO-X            PIC X(040).
           05  GRA-NOME-FINANC-X              PIC X(040).
           05  GRA-NUM-CONTRATO-X             PIC X(010).
           05  GRA-NUM-RESTRICAO-X            PIC X(010).
           05  GRA-NUM-SEQ-X                  PIC X(010).
           05  GRA-OPERADORA-X                PIC X(030).
           05  GRA-PLACA-MERC-X               PIC X(010).
           05  GRA-PLACA-X                    PIC X(010).
           05  GRA-RENAVAM-X                  PIC X(011).
           05  GRA-TIPO-RESTR-X               PIC X(006).
           05  GRA-TRANSACAO-X                PIC X(030).
           05  GRA-UF-GRAVAME-X               PIC X(002).
           05  GRA-UF-PLACA-X                 PIC X(010).
           05  GRA-ANO-TRANSACAO              PIC 9(009).
           05  GRA-ANOFABR                    PIC 9(009).
           05  GRA-ANOMOD                     PIC 9(009).
           05  GRA-CD-AGENTE                  PIC X(006).
           05  GRA-CGC-AGENTE                 PIC X(014).
           05  GRA-CHASSI-REM                 PIC X(021).
           05  GRA-CHASSI                     PIC X(021).
           05  GRA-CPF-CGC-ANTIG              PIC X(014).
           05  GRA-CPF-CGC-FINAN              PIC X(014).
           05  GRA-CPF-CGC-NOVO               PIC X(014).
           05  GRA-DIA-JULIANO                PIC X(030).
           05  GRA-DT-CONTR-VIG               PIC 9(009).
           05  GRA-DT-EMISSAO                 PIC 9(009).
           05  GRA-DT-INCLUSAO                PIC 9(009).
           05  GRA-FILLER1                    PIC X(020).
           05  GRA-FILLER2                    PIC X(020).
           05  GRA-HR-EMISSAO                 PIC 9(009).
           05  GRA-HR-INCLUSAO                PIC 9(009).
           05  GRA-NOME-AGENTE                PIC X(040).
           05  GRA-NOME-FIN-NOVO              PIC X(040).
           05  GRA-NOME-FINANC                PIC X(040).
           05  GRA-NUM-CONTRATO               PIC 9(009).
           05  GRA-NUM-RESTRICAO              PIC 9(009).
           05  GRA-NUM-SEQ                    PIC 9(009).
           05  GRA-OPERADORA                  PIC X(030).
           05  GRA-PLACA-MERC                 PIC X(010).
           05  GRA-PLACA                      PIC X(010).
           05  GRA-RENAVAM                    PIC X(011).
           05  GRA-TIPO-RESTR                 PIC X(006).
           05  GRA-TRANSACAO                  PIC X(030).
           05  GRA-UF-GRAVAME                 PIC X(002).
           05  GRA-UF-PLACA                   PIC X(010).
