      * WSD copybook for PRECADCICLODS (auto-generated)
       01  PRECADCICLODS.
           05  PRECADCICLODS-ROWID            PIC X(018).
           05  PCM-ANOMOD-X                   PIC X(004).
           05  PCM-CHASSI-ORIG-X              PIC X(021).
           05  PCM-CHASSI-X                   PIC X(021).
           05  PCM-CILINDRAD-X                PIC X(030).
           05  PCM-COMB-X                     PIC X(030).
           05  PCM-CPF-CGC-X                  PIC X(014).
           05  PCM-DATA-X                     PIC X(010).
           05  PCM-DT-ATUCAD-X                PIC X(010).
           05  PCM-HORA-X                     PIC X(006).
           05  PCM-ID-CONTR-X                 PIC X(030).
           05  PCM-MARCA-X                    PIC X(006).
           05  PCM-MOTOR-ORIG-X               PIC X(030).
           05  PCM-NRO-MOTOR-X                PIC X(030).
           05  PCM-PLACA-MERC-X               PIC X(010).
           05  PCM-PLACA-X                    PIC X(010).
           05  PCM-PROCED-X                   PIC X(030).
           05  PCM-TIPO-X                     PIC X(006).
           05  PCM-USU-ATUCAD-X               PIC X(008).
           05  PCM-USUARIO-X                  PIC X(008).
           05  PCM-ANOMOD                     PIC 9(009).
           05  PCM-CHASSI-ORIG                PIC X(021).
           05  PCM-CHASSI                     PIC X(021).
           05  PCM-CILINDRAD                  PIC X(030).
           05  PCM-COMB                       PIC X(030).
           05  PCM-CPF-CGC                    PIC X(014).
           05  PCM-DATA                       PIC X(010).
           05  PCM-DT-ATUCAD                  PIC 9(009).
           05  PCM-HORA                       PIC X(006).
           05  PCM-ID-CONTR                   PIC X(030).
           05  PCM-MARCA                      PIC X(006).
           05  PCM-MOTOR-ORIG                 PIC X(030).
           05  PCM-NRO-MOTOR                  PIC X(030).
           05  PCM-PLACA-MERC                 PIC X(010).
           05  PCM-PLACA                      PIC X(010).
           05  PCM-PROCED                     PIC X(030).
           05  PCM-TIPO                       PIC X(006).
           05  PCM-USU-ATUCAD                 PIC X(008).
           05  PCM-USUARIO                    PIC X(008).
