      * WSD copybook for PROTGEVDS (auto-generated)
       01  PROTGEVDS.
           05  PROTGEVDS-ROWID                PIC X(018).
           05  PRT-ANO-X                      PIC X(004).
           05  PRT-CHASSI-X                   PIC X(021).
           05  PRT-DESP-SSP-X                 PIC X(030).
           05  PRT-DOC-ENTR-X                 PIC X(030).
           05  PRT-DOC-SAIDA-X                PIC X(030).
           05  PRT-DT-ENTR-DOC-X              PIC X(010).
           05  PRT-DT-SAIDA-DOC-X             PIC X(010).
           05  PRT-FLAG-ENT-IMP-X             PIC X(030).
           05  PRT-FLAG-SAIDA-X               PIC X(030).
           05  PRT-HR-ENTR-DOC-X              PIC X(006).
           05  PRT-HR-SAIDA-DOC-X             PIC X(006).
           05  PRT-LETRA-X                    PIC X(030).
           05  PRT-NRO-FICHA-X                PIC X(030).
           05  PRT-NUMERO1-X                  PIC X(030).
           05  PRT-NUMERO2-X                  PIC X(030).
           05  PRT-ORG-RG-ENT-X               PIC X(030).
           05  PRT-ORG-RG-SAIDA-X             PIC X(030).
           05  PRT-PLACA-MERC-X               PIC X(010).
           05  PRT-STATUS-FICHA-X             PIC X(020).
           05  PRT-TP-DOC-ENT-X               PIC X(030).
           05  PRT-TP-DOC-SAIDA-X             PIC X(030).
           05  PRT-UF-RG-ENT-X                PIC X(002).
           05  PRT-UF-RG-SAIDA-X              PIC X(002).
           05  PRT-USU-ENTR-X                 PIC X(008).
           05  PRT-USU-SAIDA-X                PIC X(008).
           05  PRT-ANO                        PIC 9(009).
           05  PRT-CHASSI                     PIC X(021).
           05  PRT-DESP-SSP                   PIC X(030).
           05  PRT-DOC-ENTR                   PIC X(030).
           05  PRT-DOC-SAIDA                  PIC X(030).
           05  PRT-DT-ENTR-DOC                PIC 9(009).
           05  PRT-DT-SAIDA-DOC               PIC 9(009).
           05  PRT-FLAG-ENT-IMP               PIC X(030).
           05  PRT-FLAG-SAIDA                 PIC X(030).
           05  PRT-HR-ENTR-DOC                PIC 9(009).
           05  PRT-HR-SAIDA-DOC               PIC 9(009).
           05  PRT-LETRA                      PIC X(030).
           05  PRT-NRO-FICHA                  PIC X(030).
           05  PRT-NUMERO1                    PIC X(030).
           05  PRT-NUMERO2                    PIC X(030).
           05  PRT-ORG-RG-ENT                 PIC X(030).
           05  PRT-ORG-RG-SAIDA               PIC X(030).
           05  PRT-PLACA-MERC                 PIC X(010).
           05  PRT-STATUS-FICHA               PIC X(020).
           05  PRT-TP-DOC-ENT                 PIC X(030).
           05  PRT-TP-DOC-SAIDA               PIC X(030).
           05  PRT-UF-RG-ENT                  PIC X(002).
           05  PRT-UF-RG-SAIDA                PIC X(002).
           05  PRT-USU-ENTR                   PIC X(008).
           05  PRT-USU-SAIDA                  PIC X(008).
