      * WSD copybook for OBSERVCRLVDS (auto-generated)
       01  OBSERVCRLVDS.
           05  OBSERVCRLVDS-ROWID             PIC X(018).
           05  OBS-CHASSI-X                   PIC X(021).
           05  OBS-COD-OBS-X                  PIC X(006).
           05  OBS-CPF-EXCL-X                 PIC X(011).
           05  OBS-DT-EXCLUSAO-X              PIC X(010).
           05  OBS-DT-INCLUSAO-X              PIC X(010).
           05  OBS-HR-EXCLUSAO-X              PIC X(006).
           05  OBS-HR-INCLUSAO-X              PIC X(006).
           05  OBS-IDENT-REL-X                PIC X(030).
           05  OBS-IDRESTRBIN-X               PIC X(030).
           05  OBS-MANUT-X                    PIC X(030).
           05  OBS-MOTIVO-EXC-X               PIC X(030).
           05  OBS-NRO-PROC-X                 PIC X(030).
           05  OBS-PLACA-X                    PIC X(010).
           05  OBS-RENAVAM-X                  PIC X(011).
           05  OBS-RETBIN-X                   PIC X(030).
           05  OBS-SITUACAO-X                 PIC X(020).
           05  OBS-TEXTO-X                    PIC X(030).
           05  OBS-USU-EXCL-X                 PIC X(008).
           05  OBS-USU-INCL-X                 PIC X(008).
           05  OBS-VLR-NUM-X                  PIC X(030).
           05  OBS-CHASSI                     PIC X(021).
           05  OBS-COD-OBS                    PIC 9(009).
           05  OBS-CPF-EXCL                   PIC X(011).
           05  OBS-DT-EXCLUSAO                PIC 9(009).
           05  OBS-DT-INCLUSAO                PIC 9(009).
           05  OBS-HR-EXCLUSAO                PIC 9(009).
           05  OBS-HR-INCLUSAO                PIC 9(009).
           05  OBS-IDENT-REL                  PIC X(030).
           05  OBS-IDRESTRBIN                 PIC X(030).
           05  OBS-MANUT                      PIC X(030).
           05  OBS-MOTIVO-EXC                 PIC X(030).
           05  OBS-NRO-PROC                   PIC X(030).
           05  OBS-PLACA                      PIC X(010).
           05  OBS-RENAVAM                    PIC X(011).
           05  OBS-RETBIN                     PIC X(030).
           05  OBS-SITUACAO                   PIC X(020).
           05  OBS-TEXTO                      PIC X(030).
           05  OBS-USU-EXCL                   PIC X(008).
           05  OBS-USU-INCL                   PIC X(008).
           05  OBS-VLR-NUM                    PIC X(030).
